import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
import ThetLogos.WightmanAxioms

namespace ThetLogos

/-!
# ThetLogos.FreeField — the free scalar field, algebraic core

Source: the QFT rungs map (`whitepaper/qft-rungs-map-2026-10-06.md`, Rung 3).
Rung 3 is where the field's wall stands: no interacting 4D Wightman QFT has
ever been constructed (undisputed; it is the Clay problem's difficulty).
The beachhead is therefore the FREE field — the one QFT that provably exists
(Streater–Wightman 1964) — formalized as far as Mathlib (2026) allows.

**What this file IS.** The algebraic core of the free bosonic field:
- the Fock space at the algebraic level (`SymmetricAlgebra ℂ V` — Mathlib HAS
  this; the fermionic analogue `ExteriorAlgebra` also exists),
- the vacuum vector and the (algebraic) vacuum expectation functional,
- creation operators with `[a†(f), a†(g)] = 0` proved,
- the algebraic shadow of vacuum cyclicity (Wightman W5): every Fock vector
  is a polynomial in creators applied to the vacuum — PROVED via
  `SymmetricAlgebra.induction`,
- a precise per-axiom ledger (W0–W6) for the free field: each axiom is either
  proved at the algebraic level or pinned to an exact infrastructure gap.

**What this file is NOT.** A construction of the free field as an
operator-valued distribution, let alone an interacting field. The single
precise gap is named below (`fockInnerProduct`): the quantum 2-point function
lives in the Fock inner product, which Mathlib does not have. The algebraic
vacuum functional provably gives the WRONG (trivial) 2-point function
(`twoPoint_algebraic_trivial`) — this is not a bug in the file, it is the
honest location of the gap.

Honesty tiers in this file:
- **T1 (proved):** `onePoint_vanishes`, `twoPoint_algebraic_trivial`,
  `create_commute`, `vacuum_cyclic`.
- **T5 (pinned statements):** `FreeFieldWightman`, the per-axiom ledger.
-/

variable (V : Type*) [AddCommGroup V] [Module ℂ V]

/-- The bosonic Fock space at the algebraic level: the symmetric algebra
    over the one-particle space `V`. The `n`-particle sector is the
    degree-`n` piece (grading not yet in Mathlib — see ledger). -/
abbrev bosonicFock := SymmetricAlgebra ℂ V

/-- The vacuum vector: the unit of the Fock algebra. -/
def fockVacuum : bosonicFock V := 1

/-- The vacuum expectation functional at the algebraic level: the
    augmentation map killing every positive-degree element
    (`SymmetricAlgebra.algebraMapInv`). -/
def vacuumExp : bosonicFock V →ₐ[ℂ] ℂ := SymmetricAlgebra.algebraMapInv

/-- Creation operator for a one-particle state `v`: left multiplication by
    `ι v`. Raises particle number by one. -/
def create (v : V) : bosonicFock V →ₗ[ℂ] bosonicFock V :=
  LinearMap.mulLeft ℂ (SymmetricAlgebra.ι ℂ V v)

/-- The vacuum expectation of the vacuum is 1. -/
theorem vacuumExp_vacuum : vacuumExp V (fockVacuum V) = 1 := by
  simp [vacuumExp, fockVacuum]

/-- The one-point function vanishes: `⟨0| a†(v) |0⟩ = 0`.
    (This is `SymmetricAlgebra.algebraMapInv_ι`, read in field language.) -/
theorem onePoint_vanishes (v : V) :
    vacuumExp V (SymmetricAlgebra.ι ℂ V v) = 0 :=
  SymmetricAlgebra.algebraMapInv_ι v

/-- The algebraic vacuum functional gives a TRIVIAL two-point function.
    The quantum 2-point function `⟨0| φ(v)φ(w) |0⟩ = ⟪v,w⟫` lives entirely
    in the Fock inner product, which does not exist in Mathlib — this
    theorem is the precise, checked location of that gap. -/
theorem twoPoint_algebraic_trivial (v w : V) :
    vacuumExp V (SymmetricAlgebra.ι ℂ V v * SymmetricAlgebra.ι ℂ V w) = 0 := by
  rw [map_mul, onePoint_vanishes, onePoint_vanishes, mul_zero]

/-- Creation operators commute: `[a†(v), a†(w)] = 0`.
    (The `[a(v), a(w)] = 0` half needs annihilation operators, which need
    the Fock inner product — see ledger.) -/
theorem create_commute (v w : V) :
    (create V v).comp (create V w) = (create V w).comp (create V v) := by
  ext x
  unfold create
  simp only [LinearMap.comp_apply, LinearMap.mulLeft_apply]
  exact mul_left_comm _ _ _

/-- Every Fock vector lies in the algebra generated by the creators. -/
theorem mem_adjoin_range (a : bosonicFock V) :
    a ∈ Algebra.adjoin ℂ (Set.range (SymmetricAlgebra.ι ℂ V)) := by
  induction a using SymmetricAlgebra.induction with
  | algebraMap r => exact Subalgebra.algebraMap_mem _ r
  | ι x => exact Algebra.subset_adjoin ⟨x, rfl⟩
  | mul _ _ ha hb => exact Subalgebra.mul_mem _ ha hb
  | add _ _ ha hb => exact Subalgebra.add_mem _ ha hb

/-- Algebraic vacuum cyclicity (shadow of Wightman W5): every vector of the
    algebraic Fock space is a polynomial in creation operators applied to
    the vacuum. The algebra generated by the creators is everything. -/
theorem vacuum_cyclic :
    Algebra.adjoin ℂ (Set.range (SymmetricAlgebra.ι ℂ V)) = ⊤ :=
  eq_top_iff.mpr fun _ _ => mem_adjoin_range V _

/-!
## Per-axiom ledger: the free field against W0–W6

Verdicts for the free scalar field. "Proved" means in this file (T1);
"blocked" names the exact gap and labels it infrastructure (missing from
Mathlib 2026) vs. mathematical (open in the literature).

- **W0 (Hilbert space):** BLOCKED — infrastructure. Needs the Hilbert
  completion of `SymmetricAlgebra ℂ V` under the Fock inner product
  `⟪ι(v₁)⋯ι(vₙ), ι(w₁)⋯ι(wₙ)⟫ = per(⟪vᵢ,wⱼ⟫)` (permanent formula, n!
  normalization). The inner product itself is absent from Mathlib; without
  it there is no completion to take.
- **W1 (fields as operator-valued tempered distributions):** BLOCKED —
  infrastructure, two gaps. (a) No Schwartz distribution theory in Mathlib
  (no `𝒮`, no `𝒮'`). (b) The annihilation operator `a(f)` is the adjoint of
  `create f`, hence needs the Fock inner product (same gap as W0). The
  smeared free field `φ(f) = a(f) + a†(f)` cannot currently be stated.
- **W2 (Poincaré covariance):** BLOCKED — infrastructure. Needs the
  one-particle representation on `L²(Hₘ⁺, dμ)` (positive mass shell with
  Lorentz-invariant measure — buildable in principle from Mathlib's measure
  theory, a large construction) and second quantization `Γ(U₁)` (needs W0).
- **W3 (spectrum condition):** geometry T1 — `forwardLightCone_convexCone`
  in `WightmanAxioms.lean`. The operator statement (joint spectrum of the
  energy-momentum operators inside the cone) is BLOCKED on W0/W1.
- **W4 (locality):** BLOCKED — infrastructure. The c-number commutator
  `[φ(f), φ(g)] = iΔ(f,g)·1` needs the full CCR (annihilation — see W1) and
  the Pauli–Jordan distribution `Δ` (needs Schwartz theory — see W1).
  Algebraic shadow proved: `[create v, create w] = 0` (`create_commute`).
- **W5 (vacuum cyclicity):** algebraic shadow PROVED (`vacuum_cyclic`).
  The Hilbert-space density statement is BLOCKED on W0.
- **W6 (clustering):** BLOCKED — infrastructure. Needs the explicit
  2-point function `Δ₊` and its spacelike decay (distribution theory +
  Bessel-function analysis, absent from Mathlib).
-/

/-- The free field's Wightman verification, pinned: the conjunction of
    W0–W6 for the free scalar field. **Open as a formalization target**
    (blocked on the infrastructure gaps above); the mathematical content
    (Streater–Wightman 1964) is established in the literature. -/
def FreeFieldWightman : Prop := ∃ _ : WightmanAxioms, True

#print axioms onePoint_vanishes
#print axioms twoPoint_algebraic_trivial
#print axioms create_commute
#print axioms vacuum_cyclic

end ThetLogos
