import Mathlib.Data.Matrix.Mul
import Mathlib.LinearAlgebra.Matrix.ConjTranspose
import Mathlib.Basic.Complex.Basic
import Mathlib.Tactic
import ThetLogos.TRO
import ThetLogos.CFKernelBase
import ThetLogos.MartinettiRep

open scoped ComplexConjugate

/-!
# ThetLogos.XYZTripotents — Open Problem 2: XYZ tripotent operators (Tiers T3/T5)

Roadmap target from the external review of `whitepaper/grand-unified-theory.md`:
the cleanest near-term test of the Tet/thet ontology is to either

- (success) construct three tripotent operators X, Y, Z whose generated TRO
  contains the SM representation data, or
- (failure) prove that no such triple exists.

What is done here (T3, machine-checked):
- `Tripotent`: the tripotent equation for the TRO ternary product;
- elementary tripotent lemmas (zero, one, orthogonal projections, scalars);
- the generated-TRO predicate `MemGenTRO` and its diagonal-closure lemma;
- a proved partial negative result: no triple of *diagonal* tripotents can
  generate the SM representation (`no_diagonal_xyz_tripotents`), ruling out
  the natural sector-projection candidate triple `(cfMat, 1 - cfMat, 1)`
  (`sector_triple_fails`).

What is open (T5): the general existence statement `xyz_tripotents_exist`
is a single documented `sorry`. No new axioms are introduced.
-/

namespace ThetLogos

/-! ## §1. Tripotents of the ternary product -/

/-- A tripotent of the matrix ternary product: {{e, e, e}} = e. Tier T2. -/
def Tripotent {n : ℕ} (e : Matrix (Fin n) (Fin n) ℂ) : Prop :=
  ternaryMat e e e = e

/-- Zero is a tripotent. Tier T3 (proved). -/
theorem tripotent_zero {n : ℕ} : Tripotent (0 : Matrix (Fin n) (Fin n) ℂ) := by
  unfold Tripotent
  simp [ternaryMat]

/-- One is a tripotent. Tier T3 (proved). -/
theorem tripotent_one {n : ℕ} : Tripotent (1 : Matrix (Fin n) (Fin n) ℂ) := by
  unfold Tripotent
  simp [ternaryMat]

/-- Orthogonal projections are tripotents: Pᴴ = P and P² = P give
    {{P,P,P}} = P·Pᴴ·P = P³ = P. Tier T3 (proved). -/
theorem tripotent_of_isProj {n : ℕ} (P : Matrix (Fin n) (Fin n) ℂ)
    (hH : P.conjTranspose = P) (hP : P * P = P) : Tripotent P := by
  unfold Tripotent
  simp only [ternaryMat, hH]
  rw [Matrix.mul_assoc, hP, hP]

/-- Scalar tripotents: {{a,a,a}} = a iff a = 0 or ‖a‖² = 1. Tier T3 (proved). -/
theorem scalar_tripotent_iff (a : ℂ) :
    ternary a a a = a ↔ a = 0 ∨ Complex.normSq a = 1 := by
  have key : ∀ z : ℂ, z * star z * z = (Complex.normSq z : ℂ) * z := by
    intro z
    have hstar : star z = conj z := rfl
    rw [hstar, Complex.mul_conj]
  constructor
  · intro h
    simp only [ternary] at h
    rw [key] at h
    by_cases ha : a = 0
    · exact Or.inl ha
    · right
      have h2 : (Complex.normSq a : ℂ) * a = 1 * a := by rw [h, one_mul]
      have h3 : (Complex.normSq a : ℂ) = 1 := mul_right_cancel₀ ha h2
      exact_mod_cast h3
  · rintro (rfl | h)
    · simp [ternary]
    · simp only [ternary]
      rw [key, h]
      simp

/-! ## §2. The C_F sector projection is a tripotent -/

/-- cfMat is self-adjoint (diagonal with 0/1 entries). Tier T3 (proved). -/
theorem cfMat_conjTranspose : cfMat.conjTranspose = cfMat := by
  unfold cfMat
  rw [Matrix.diagonal_conjTranspose]
  congr 1
  funext i
  rcases cfIndicator_mem i with h | h <;> simp [h, Pi.star_apply]

/-- cfMat is idempotent (indicator values square to themselves). Tier T3 (proved). -/
theorem cfMat_mul_self : cfMat * cfMat = cfMat := by
  unfold cfMat
  rw [Matrix.diagonal_mul_diagonal]
  congr 1
  funext i
  rcases cfIndicator_mem i with h | h <;> simp [h]

/-- The C_F sector projection is a tripotent. Tier T3 (proved). -/
theorem tripotent_cfMat : Tripotent cfMat :=
  tripotent_of_isProj cfMat cfMat_conjTranspose cfMat_mul_self

/-- The complementary sector projection is self-adjoint. Tier T3 (proved). -/
theorem one_sub_cfMat_conjTranspose : (1 - cfMat).conjTranspose = 1 - cfMat := by
  rw [Matrix.conjTranspose_sub, Matrix.conjTranspose_one, cfMat_conjTranspose]

/-- The complementary sector projection is idempotent. Tier T3 (proved). -/
theorem one_sub_cfMat_mul_self : (1 - cfMat) * (1 - cfMat) = 1 - cfMat := by
  calc (1 - cfMat) * (1 - cfMat)
      = 1 * 1 - 1 * cfMat - (cfMat * 1 - cfMat * cfMat) := by
        rw [sub_mul, mul_sub, mul_sub]
    _ = 1 - cfMat - (cfMat - cfMat) := by
        simp only [one_mul, mul_one, cfMat_mul_self]
    _ = 1 - cfMat := by abel

/-- The complementary sector projection is a tripotent. Tier T3 (proved). -/
theorem tripotent_one_sub_cfMat : Tripotent (1 - cfMat) :=
  tripotent_of_isProj _ one_sub_cfMat_conjTranspose one_sub_cfMat_mul_self

/-! ## §3. The generated TRO and the diagonal trap -/

/-- Membership in the TRO generated by a set S: closure under the ternary
    product. Tier T2. -/
inductive MemGenTRO {n : ℕ} (S : Set (Matrix (Fin n) (Fin n) ℂ)) :
    Matrix (Fin n) (Fin n) ℂ → Prop
  | of_mem (a : Matrix (Fin n) (Fin n) ℂ) : a ∈ S → MemGenTRO S a
  | of_ternary (a b c : Matrix (Fin n) (Fin n) ℂ) :
      MemGenTRO S a → MemGenTRO S b → MemGenTRO S c →
      MemGenTRO S (ternaryMat a b c)

/-- The ternary product of diagonal matrices is diagonal. Tier T3 (proved). -/
theorem ternaryMat_diagonal {n : ℕ} (d₁ d₂ d₃ : Fin n → ℂ) :
    ternaryMat (Matrix.diagonal d₁) (Matrix.diagonal d₂) (Matrix.diagonal d₃) =
    Matrix.diagonal fun i => d₁ i * star (d₂ i) * d₃ i := by
  simp only [ternaryMat, Matrix.diagonal_conjTranspose, Matrix.diagonal_mul_diagonal,
    Pi.star_apply]

/-- A TRO generated by diagonal matrices contains only diagonal matrices.
    Tier T3 (proved). -/
theorem memGenTRO_diagonal {n : ℕ} (S : Set (Matrix (Fin n) (Fin n) ℂ))
    (hS : ∀ a ∈ S, ∃ d, a = Matrix.diagonal d)
    (a : Matrix (Fin n) (Fin n) ℂ) (h : MemGenTRO S a) :
    ∃ d, a = Matrix.diagonal d := by
  induction h with
  | of_mem a ha => exact hS a ha
  | of_ternary a b c _ _ _ iha ihb ihc =>
    obtain ⟨d₁, rfl⟩ := iha
    obtain ⟨d₂, rfl⟩ := ihb
    obtain ⟨d₃, rfl⟩ := ihc
    exact ⟨_, ternaryMat_diagonal d₁ d₂ d₃⟩

/-! ## §4. The SM representation is not diagonal -/

/-- The H-sector generator `smGen 1 = genH 0` has a nonzero off-diagonal entry:
    the Pauli σ₁ doublet at indices 0, 1. Tier T3 (proved). -/
theorem smGen_one_offdiag :
    smGen (1 : Fin 12) (⟨0, by norm_num⟩ : I32) (⟨1, by norm_num⟩ : I32) = 1 := by
  have h1 : smGen (1 : Fin 12) = genH 0 := rfl
  rw [h1]
  norm_num [genH, pauli]

/-- `smGen 1` is not a diagonal matrix. Tier T3 (proved). -/
theorem smGen_one_not_diagonal : ¬ ∃ d : I32 → ℂ, smGen 1 = Matrix.diagonal d := by
  rintro ⟨d, hd⟩
  have h10 := smGen_one_offdiag
  rw [hd, Matrix.diagonal_apply_ne _ (by decide : (⟨0, by norm_num⟩ : I32) ≠ ⟨1, by norm_num⟩)] at h10
  exact one_ne_zero h10.symm

/-! ## §5. Partial negative result: the diagonal triple cannot work -/

/-- No triple of diagonal tripotents generates the SM representation data:
    their TRO stays diagonal, but `smGen 1` is not diagonal. Tier T3 (proved). -/
theorem no_diagonal_xyz_tripotents (X Y Z : Matrix I32 I32 ℂ)
    (hX : ∃ d, X = Matrix.diagonal d)
    (hY : ∃ d, Y = Matrix.diagonal d)
    (hZ : ∃ d, Z = Matrix.diagonal d) :
    ¬ ∀ g : Fin 12, MemGenTRO ({X, Y, Z} : Set (Matrix I32 I32 ℂ)) (smGen g) := by
  intro hall
  have hS : ∀ a ∈ ({X, Y, Z} : Set (Matrix I32 I32 ℂ)), ∃ d, a = Matrix.diagonal d := by
    intro a ha
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
    rcases ha with rfl | rfl | rfl
    · exact hX
    · exact hY
    · exact hZ
  have hdiag := memGenTRO_diagonal _ hS _ (hall 1)
  exact smGen_one_not_diagonal hdiag

/-- The complementary sector projection is diagonal. Tier T3 (proved). -/
theorem one_sub_cfMat_diagonal :
    ∃ d : I32 → ℂ, (1 : Matrix I32 I32 ℂ) - cfMat = Matrix.diagonal d := by
  refine ⟨fun i => 1 - cfIndicator i, ?_⟩
  have h1 : (1 : Matrix I32 I32 ℂ) = Matrix.diagonal 1 := Matrix.diagonal_one'.symm
  have h2 : cfMat = Matrix.diagonal cfIndicator := rfl
  rw [h1, h2, Matrix.diagonal_sub]
  congr 1

/-- The natural sector-projection triple (C_F support, its complement, and the
    identity) consists of genuine tripotents — but it cannot generate the SM
    representation: the first concrete candidate ruled out. Tier T3 (proved). -/
theorem sector_triple_fails :
    ¬ ∀ g : Fin 12, MemGenTRO ({cfMat, 1 - cfMat, 1} : Set (Matrix I32 I32 ℂ)) (smGen g) :=
  no_diagonal_xyz_tripotents cfMat (1 - cfMat) 1
    ⟨cfIndicator, rfl⟩ one_sub_cfMat_diagonal ⟨1, Matrix.diagonal_one'.symm⟩

/-! ## §8. gammaF and UJ are tripotents -/

/-- UJ has real (0/1) entries, hence is fixed by entrywise `star`.
    Tier T3 (proved). -/
theorem UJ_entry_star (i j : I32) : star (UJ j i) = UJ j i := by
  rw [UJ_apply]
  unfold UJ_matrix
  split_ifs with h
  · exact star_one _
  · exact star_zero _

/-- UJ is symmetric at the entry level. Tier T3 (proved). -/
theorem UJ_symmetric_entry (i j : I32) : UJ j i = UJ i j := by
  rw [UJ_apply, UJ_apply]
  unfold UJ_matrix
  split_ifs with h1 h2 h2
  · rfl
  · exfalso
    exact h2 (by rw [h1, partner_involutive])
  · exfalso
    exact h1 (by rw [h2, partner_involutive])
  · rfl

/-- UJ is self-adjoint: UJᴴ = UJ (real symmetric). Tier T3 (proved). -/
theorem UJ_conjTranspose_eq : UJ.conjTranspose = UJ := by
  ext i j
  rw [Matrix.conjTranspose_apply, UJ_entry_star]
  exact UJ_symmetric_entry i j

/-- The grading operator is a tripotent: γ_F self-adjoint and involutive
    give {{γ_F,γ_F,γ_F}} = γ_F³ = γ_F. Tier T3 (proved). -/
theorem tripotent_gammaF : Tripotent gammaF := by
  unfold Tripotent ternaryMat
  rw [gammaF_self_adjoint, Matrix.mul_assoc, gammaF_involutive, Matrix.mul_one]

/-- The real structure is a tripotent: UJ self-adjoint and involutive
    give {{UJ,UJ,UJ}} = UJ³ = UJ. Tier T3 (proved). -/
theorem tripotent_UJ : Tripotent UJ := by
  unfold Tripotent ternaryMat
  rw [UJ_conjTranspose_eq, Matrix.mul_assoc, UJ_mul_self, Matrix.mul_one]

/-- UJ-conjugation commutes with `conjTranspose` (UJ is self-adjoint).
    Tier T3 (proved). -/
theorem UJ_conj_conjTranspose (M : Matrix I32 I32 ℂ) :
    UJ * M.conjTranspose * UJ = (UJ * M * UJ).conjTranspose := by
  simp only [Matrix.conjTranspose_mul, UJ_conjTranspose_eq, Matrix.mul_assoc]

/-- UJ-conjugation distributes over products (local copy; the same statement
    is `UJ_conj_mul` in `InnerFluctuations`). Tier T3 (proved). -/
theorem UJ_conj_mul_aux (X Y : Matrix I32 I32 ℂ) :
    UJ * (X * Y) * UJ = (UJ * X * UJ) * (UJ * Y * UJ) := by
  have hUJ : UJ * UJ = 1 := UJ_mul_self
  calc UJ * (X * Y) * UJ
      = UJ * X * Y * UJ := by simp only [Matrix.mul_assoc]
    _ = UJ * X * (UJ * UJ) * Y * UJ := by rw [hUJ]; simp only [Matrix.mul_one]
    _ = (UJ * X * UJ) * (UJ * Y * UJ) := by simp only [Matrix.mul_assoc]

/-- The ternary product distributes over UJ-conjugation:
    {{UJXUJ, UJY UJ, UJZUJ}} = UJ{{X,Y,Z}}UJ. Tier T3 (proved). -/
theorem UJ_ternary_conj (X Y Z : Matrix I32 I32 ℂ) :
    ternaryMat (UJ * X * UJ) (UJ * Y * UJ) (UJ * Z * UJ)
      = UJ * ternaryMat X Y Z * UJ := by
  unfold ternaryMat
  rw [← UJ_conj_conjTranspose, ← UJ_conj_mul_aux, ← UJ_conj_mul_aux]

/-- Tripotents are preserved under UJ-conjugation. Tier T3 (proved). -/
theorem tripotent_UJ_conj (X : Matrix I32 I32 ℂ) (hX : Tripotent X) :
    Tripotent (UJ * X * UJ) := by
  unfold Tripotent at *
  rw [UJ_ternary_conj, hX]

/-! ## §9. Diagonal tripotents and genC -/

/-- A diagonal matrix is a tripotent when each diagonal entry is a scalar
    tripotent. Tier T3 (proved). -/
theorem tripotent_diagonal {n : ℕ} (d : Fin n → ℂ)
    (hd : ∀ i, d i * star (d i) * d i = d i) :
    Tripotent (Matrix.diagonal d) := by
  unfold Tripotent
  rw [ternaryMat_diagonal]
  have hfun : (fun i => d i * star (d i) * d i) = d := funext hd
  rw [hfun]

/-- Diagonal entries with `normSq` 0 or 1 give tripotents. Tier T3 (proved). -/
theorem tripotent_diagonal_normSq {n : ℕ} (d : Fin n → ℂ)
    (hd : ∀ i, d i = 0 ∨ Complex.normSq (d i) = 1) :
    Tripotent (Matrix.diagonal d) := by
  apply tripotent_diagonal
  intro i
  have key : ∀ z : ℂ, z * star z * z = (Complex.normSq z : ℂ) * z := by
    intro z
    have hstar : star z = conj z := rfl
    rw [hstar, Complex.mul_conj]
  rcases hd i with h | h
  · rw [h]; simp
  · rw [key, h]; simp

/-- genC is diagonal. Tier T3 (proved). -/
theorem genC_eq_diagonal : genC = Matrix.diagonal (fun i : I32 => genC i i) := by
  ext i j
  by_cases h : i = j
  · subst h
    rw [Matrix.diagonal_apply_eq]
  · rw [Matrix.diagonal_apply_ne _ h, genC_apply_ne h]

/-- Each diagonal entry of genC is `Complex.I` or `0`. Tier T3 (proved). -/
theorem genC_diag_I_or_zero (i : I32) :
    genC i i = Complex.I ∨ genC i i = 0 := by
  rw [genC_diag_val]
  split_ifs <;> simp

/-- The colour generator is a tripotent: its diagonal entries are `i` (with
    `normSq = 1`) or `0`. Tier T3 (proved). -/
theorem tripotent_genC : Tripotent genC := by
  rw [genC_eq_diagonal]
  apply tripotent_diagonal_normSq
  intro i
  rcases genC_diag_I_or_zero i with h | h
  · rw [h]; exact Or.inr Complex.normSq_I
  · rw [h]; exact Or.inl rfl

/-! ## §10. Conjugation cannot leave the diagonal world -/

/-- Conjugation of a diagonal matrix by a diagonal matrix is diagonal.
    Tier T3 (proved). -/
theorem diag_conj_diagonal (d e : I32 → ℂ) :
    Matrix.diagonal d * Matrix.diagonal e * (Matrix.diagonal d).conjTranspose
      = Matrix.diagonal (fun i => d i * e i * star (d i)) := by
  simp only [Matrix.diagonal_conjTranspose, Matrix.diagonal_mul_diagonal,
    Pi.star_apply]

/-- UJ-conjugation preserves diagonality: it permutes the diagonal entries
    by the partner involution. Tier T3 (proved). -/
theorem UJ_conj_diagonal (e : I32 → ℂ) :
    UJ * Matrix.diagonal e * UJ = Matrix.diagonal (fun i => e (partner i)) := by
  have hmul : ∀ a b : I32, (UJ * Matrix.diagonal e) a b = UJ a b * e b := by
    intro a b
    simp only [Matrix.mul_apply, Matrix.diagonal_apply, mul_ite, mul_zero,
      Finset.sum_ite_eq', Finset.mem_univ, ite_true]
  have hUJ : ∀ a b : I32, UJ a b = (if b = partner a then (1:ℂ) else 0) := by
    intro a b; rw [UJ_apply]; rfl
  ext i j
  have h2 : (UJ * Matrix.diagonal e * UJ) i j
      = ∑ k, (UJ i k * e k) * UJ k j := by
    simp only [Matrix.mul_apply, hmul]
  rw [h2, Matrix.diagonal_apply,
    show (∑ k, (UJ i k * e k) * UJ k j)
      = ∑ k, (if k = partner i then e k * UJ k j else 0) from by
      apply Finset.sum_congr rfl
      intro k _
      rw [hUJ i k]
      by_cases hk : k = partner i <;> simp [hk],
    Finset.sum_ite_eq', hUJ, partner_involutive]
  by_cases h : i = j
  · subst h; simp
  · simp [h, Ne.symm h]

/-- γ_F is diagonal. Tier T3 (proved). -/
theorem gammaF_eq_diagonal : gammaF = Matrix.diagonal (fun i : I32 => gammaF i i) := by
  ext i j
  by_cases h : i = j
  · subst h
    rw [Matrix.diagonal_apply_eq]
  · rw [Matrix.diagonal_apply_ne _ h, gammaF_apply_ne h]

/-- UJ-conjugation of γ_F stays diagonal. Tier T3 (proved). -/
theorem UJ_conj_gammaF_diagonal :
    ∃ e : I32 → ℂ, UJ * gammaF * UJ = Matrix.diagonal e := by
  rw [gammaF_eq_diagonal]
  exact ⟨_, UJ_conj_diagonal _⟩

/-- Diagonal-unitary conjugation of γ_F stays diagonal. Tier T3 (proved). -/
theorem diagUnitary_conj_gammaF_diagonal (d : I32 → ℂ) :
    ∃ e : I32 → ℂ,
      Matrix.diagonal d * gammaF * (Matrix.diagonal d).conjTranspose
        = Matrix.diagonal e := by
  rw [gammaF_eq_diagonal]
  exact ⟨_, diag_conj_diagonal d _⟩

/-- The concrete triple `(γ_F, UJγ_FUJ, 1)` is dead: all three generators are
    diagonal, so the generated TRO is diagonal and misses `smGen 1`.
    Tier T3 (proved). -/
theorem triple_gammaF_UJconj_one_fails :
    ¬ ∀ g : Fin 12,
      MemGenTRO ({gammaF, UJ * gammaF * UJ, 1} : Set (Matrix I32 I32 ℂ)) (smGen g) := by
  apply no_diagonal_xyz_tripotents
  · exact ⟨_, gammaF_eq_diagonal⟩
  · obtain ⟨e, he⟩ := UJ_conj_gammaF_diagonal
    exact ⟨e, he⟩
  · exact ⟨fun _ => 1, Matrix.diagonal_one.symm⟩

/-! ## §11. Sector reach: H-generators cannot leave indices 0–7 -/

/-- Ternary products preserve index support: if `a, b, c` have all nonzero
    entries on indices satisfying `P`, so does `ternaryMat a b c`.
    Tier T3 (proved). -/
theorem memGenTRO_supported (P : I32 → Prop) (S : Set (Matrix I32 I32 ℂ))
    (hS : ∀ M ∈ S, ∀ i j : I32, M i j ≠ 0 → P i ∧ P j)
    (M : Matrix I32 I32 ℂ) (hM : MemGenTRO S M) :
    ∀ i j : I32, M i j ≠ 0 → P i ∧ P j := by
  induction hM with
  | of_mem a ha => exact hS a ha
  | of_ternary a b c _ _ _ iha ihb ihc =>
    intro i j hij
    unfold ternaryMat at hij
    rw [Matrix.mul_apply] at hij
    obtain ⟨k, _, hk⟩ := Finset.exists_ne_zero_of_sum_ne_zero hij
    have hc : c k j ≠ 0 := fun h0 => hk (by rw [h0, mul_zero])
    have hab : (a * b.conjTranspose) i k ≠ 0 := fun h0 => hk (by rw [h0, zero_mul])
    rw [Matrix.mul_apply] at hab
    obtain ⟨l, _, hl⟩ := Finset.exists_ne_zero_of_sum_ne_zero hab
    have ha : a i l ≠ 0 := fun h0 => hl (by rw [h0, zero_mul])
    have hbT : (b.conjTranspose) l k ≠ 0 := fun h0 => hl (by rw [h0, mul_zero])
    have hb : b k l ≠ 0 := by
      intro h0
      apply hbT
      rw [Matrix.conjTranspose_apply, h0]
      exact star_zero _
    obtain ⟨hPi, -⟩ := iha i l ha
    obtain ⟨-, hPj⟩ := ihc k j hc
    exact ⟨hPi, hPj⟩

/-- The (18, 20) entry of `genM 0` is `1`. Tier T3 (proved). -/
theorem genM_zero_18_20 : genM 0 ⟨18, by norm_num⟩ ⟨20, by norm_num⟩ = 1 := by
  have h18 : tripletOf ((⟨18, by norm_num⟩ : I32).val)
      = some ((0 : Fin 4), (0 : Fin 3)) := by decide
  have h20 : tripletOf ((⟨20, by norm_num⟩ : I32).val)
      = some ((0 : Fin 4), (1 : Fin 3)) := by decide
  unfold genM
  rw [h18, h20]
  dsimp only
  rw [if_pos rfl]
  unfold gellMann
  rfl

/-- No-go: the H-sector triple cannot reach the M-sector. Every matrix in the
    TRO generated by {genH 0, genH 1, genH 2} is supported on indices 0–7
    (by `genH_supp_block` and support preservation), but `smGen 4 = genM 0`
    has the nonzero entry (18, 20). Tier T3 (proved). -/
theorem triple_genH_cannot_reach_genM :
    ¬ MemGenTRO ({genH 0, genH 1, genH 2} : Set (Matrix I32 I32 ℂ)) (smGen 4) := by
  intro hmem
  have hS : ∀ M ∈ ({genH 0, genH 1, genH 2} : Set (Matrix I32 I32 ℂ)),
      ∀ i j : I32, M i j ≠ 0 → (i.val < 8 ∧ j.val < 8) := by
    intro M hM
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hM
    rcases hM with rfl | rfl | rfl
    · intro i j hij
      have h := genH_supp_block 0 i j hij
      exact ⟨h.1, h.2.1⟩
    · intro i j hij
      have h := genH_supp_block 1 i j hij
      exact ⟨h.1, h.2.1⟩
    · intro i j hij
      have h := genH_supp_block 2 i j hij
      exact ⟨h.1, h.2.1⟩
  have hsupp := memGenTRO_supported (fun i : I32 => i.val < 8)
    ({genH 0, genH 1, genH 2} : Set (Matrix I32 I32 ℂ)) hS (smGen 4) hmem
  have hentry : smGen 4 ⟨18, by norm_num⟩ ⟨20, by norm_num⟩ ≠ 0 := by
    have h4 : smGen 4 = genM 0 := rfl
    rw [h4, genM_zero_18_20]
    exact one_ne_zero
  have hcon := hsupp _ _ hentry
  norm_num at hcon

/-! ## §6. Open Problem 2: the XYZ existence statement -/

/-- **Open Problem 2 (Tier T5 — open).** XYZ tripotent existence.

    Success criterion (external review): an explicit triple (X, Y, Z) of
    tripotents whose generated TRO contains the SM representation data
    `smGen` (the repaired Martinetti 12-generator family).

    Failure criterion: a proof that no such triple exists.

    Status: the diagonal case is ruled out above (`no_diagonal_xyz_tripotents`,
    `sector_triple_fails`); the general statement is open. In particular the
    natural sector-projection candidates from the C_F decomposition do not
    suffice — any successful triple must reach the off-diagonal H/M-sector
    generators. -/
theorem xyz_tripotents_exist :
    ∃ X Y Z : Matrix I32 I32 ℂ,
      Tripotent X ∧ Tripotent Y ∧ Tripotent Z ∧
      ∀ g : Fin 12, MemGenTRO ({X, Y, Z} : Set (Matrix I32 I32 ℂ)) (smGen g) := by
  sorry

/-! ## §7. Candidate exploration (record)

The natural first candidate triple is the sector-projection triple
`(cfMat, 1 - cfMat, 1)`:
- `cfMat` is the C_F support projection from `CFKernelBase` (the diagonal
  projector onto the C/H support {0,…,17,24,25});
- `1 - cfMat` is the complementary projection;
- `1` is the identity.

All three are proved tripotents above (`tripotent_cfMat`,
`tripotent_one_sub_cfMat`, `tripotent_one`). However, all three are diagonal,
and `memGenTRO_diagonal` shows the TRO they generate contains only diagonal
matrices — while `smGen 1 = genH 0` carries the off-diagonal Pauli-σ₁ doublet
(`smGen_one_offdiag`). Hence `sector_triple_fails`: this candidate provably
cannot reach the SM representation data.

What this tells us: any successful XYZ triple must generate off-diagonal
content — the tripotents cannot all lie in the diagonal (Cartan) subalgebra.
The H-sector (Pauli doublets) and M-sector (Gell-Mann triplets) generators are
the obstruction.

## Second wave (2026-09-28): gammaF, UJ, genC, and conjugates

`tripotent_gammaF`: the grading operator is a tripotent (self-adjoint +
involutive give γ_F³ = γ_F). `tripotent_UJ`: the real structure is a tripotent
(`UJ_conjTranspose_eq`: UJ is real symmetric; `UJ_mul_self`: involutive).
Tripotence is preserved under UJ-conjugation (`tripotent_UJ_conj`, via the
distribution lemma `UJ_ternary_conj`).

`tripotent_genC`: the colour generator is a tripotent — it is diagonal
(`genC_eq_diagonal`) with entries `i` (`normSq = 1`) or `0`
(`tripotent_diagonal_normSq`).

Conjugation no-go (§10): diagonal-unitary conjugation preserves diagonality
(`diag_conj_diagonal`) and UJ-conjugation preserves diagonality, permuting
entries by the partner involution (`UJ_conj_diagonal`). Since `gammaF` is
diagonal (`gammaF_eq_diagonal`), the "conjugate" escape route is closed for
the diagonal class: e.g. `triple_gammaF_UJconj_one_fails` kills the concrete
triple `(γ_F, UJγ_FUJ, 1)` — all three generators are diagonal, so the
generated TRO is diagonal and misses `smGen 1`.

Sector no-go (§11): ternary products preserve index support
(`memGenTRO_supported`). The H-generators live on indices 0–7
(`genH_supp_block`), while `genM 0` has the nonzero entry (18, 20)
(`genM_zero_18_20`). Hence `triple_genH_cannot_reach_genM`: the H-sector
triple `{genH 0, genH 1, genH 2}` provably cannot reach `smGen 4`. Any viable
XYZ triple must therefore draw generators from *multiple* sectors — a single
sector's tripotents are trapped by the support invariant.

Net: the diagonal class and the single-sector class are both machine-refuted.
The remaining search space needs tripotents whose ternary closure genuinely
mixes sectors (e.g. involving UJ itself, which is off-diagonal, together with
sector generators) — still open (see `xyz_tripotents_exist`).

## Third wave (2026-09-28): rubric R1–R5, R4/R5 no-gos, partial reachability

Screening rubric §12 codifies R1–R3 from the proved kills and adds two new
rules proved below.

R4 (§13, `no_UJ_diagonal_pair_reach`): the target (a) families `{UJ, genC,
cfMat}` and `{UJ, gammaF, genC}` are DEAD for `smGen 1` — proved, not merely
attempted. Pair support (`i = j ∨ j = partner i`) is preserved by ternary
products (`pairSupport_ternary` via `pairSupport_mul_star`); UJ and diagonal
matrices satisfy it, but `smGen 1`'s nonzero (0, 1) entry (`smGen_one_offdiag`)
violates it (`0 ≠ 1`, `1 ≠ partner 0`).

R5 (§14, `no_gaussInt_triple_reaches_genM7`): the strongest no-go yet. No
`ℤ[i]`-valued triple reaches `smGen 11 = genM 7`: Gaussian-integer entries
are preserved by `star`/addition/multiplication (`gaussInt_star`,
`gaussInt_add`, `gaussInt_mul`), hence by ternary products
(`gaussInt_ternary`) and the whole generated TRO (`memGenTRO_gaussInt`) —
but `genM 7` carries the entry `1/√3` at (18, 18) (`genM_seven_18_18`),
which is not a Gaussian integer (`not_gaussInt_inv_sqrt3`). Kills every
`ℤ[i]`-valued candidate family at once.

Positive (§15): the valid tripotent triple `{genC, UJ, gammaF}` (all three
proved tripotents) reaches `smGen 0 = genC` by membership
(`triple_genC_UJ_gammaF_reaches_smGen0`) — but is R4-dead for `smGen 1`
(`triple_genC_UJ_gammaF_cannot_reach_smGen1`). Partial reachability, honestly
separated into proved lemmas.

Rubric prediction: a viable triple must contain UJ *and* a non-diagonal,
non-pair-support tripotent. Next positive step is to prove `Tripotent
(genH k)` / `Tripotent (genM a)` and test mixed triples like
`{genH 0, UJ, genM 0}`.

Net third wave: 5 rubric rules (R1–R5), 2 new machine-checked no-go families,
1 partial positive (1 of 12 generators). `xyz_tripotents_exist` still open
(single documented T5 sorry).
-/

/-! ## §12. Candidate-triple screening rubric (R1–R5)

Every candidate triple `(X, Y, Z)` proposed for `xyz_tripotents_exist` must be
screened against the proved no-go theorems. A triple failing any rule is dead
on arrival: its generated TRO provably cannot reach all twelve `smGen`
generators.

**R1 — Diagonal trap** (`no_diagonal_xyz_tripotents`, §5). Not all three of
X, Y, Z may be diagonal: a diagonal triple generates only diagonal matrices
(`memGenTRO_diagonal`), but `smGen 1 = genH 0` is off-diagonal
(`smGen_one_offdiag`, `smGen_one_not_diagonal`).

**R2 — Conjugation trap** (`triple_gammaF_UJconj_one_fails`, §10).
UJ-conjugation merely permutes diagonal entries (`UJ_conj_diagonal`), so
conjugating diagonal tripotents does not escape diagonality.

**R3 — Sector trap** (`triple_genH_cannot_reach_genM`, §11). Ternary products
preserve index support (`memGenTRO_supported`); a triple confined to one
index sector cannot reach another sector.

**R4 — Pair-support trap** (`no_UJ_diagonal_pair_reach`, §13). A triple
`{UJ, D₁, D₂}` with D₁, D₂ diagonal generates only matrices supported on the
diagonal or the partner anti-diagonal (`memGenTRO_pairSupport`); hence it
cannot reach `smGen 1`, whose (0, 1) entry is nonzero.

**R5 — Entry-ring trap** (`no_gaussInt_triple_reaches_genM7`, §14). A triple
of Gaussian-integer-entry matrices generates only Gaussian-integer-entry
matrices (`memGenTRO_gaussInt`); hence it cannot reach `genM 7`, which
carries the entry `1/√3` at (18, 18) (`genM_seven_18_18`,
`not_gaussInt_inv_sqrt3`).
-/

/-! ## §13. R4 — Pair-support invariant: UJ plus diagonals cannot reach smGen 1

The §7 target families `{UJ, genC, cfMat}` and `{UJ, gammaF, genC}` pair the
off-diagonal UJ with two diagonal tripotents. They are dead by a support
invariant strictly between "diagonal" (R1) and "index support" (R3): every
matrix in the generated TRO is supported on the *pair support* — nonzero
entries only where `i = j` (diagonal) or `j = partner i` (partner
anti-diagonal). UJ lives on the partner anti-diagonal (`UJ_support_iff`);
diagonal matrices live on the diagonal; ternary products preserve pair
support (`pairSupport_ternary`, via the helper `pairSupport_mul_star`). But
`smGen 1 = genH 0` has the nonzero entry (0, 1) (`smGen_one_offdiag`) with
`0 ≠ 1` and `1 ≠ partner 0`, violating pair support. Hence
`no_UJ_diagonal_pair_reach`: no `{UJ, D₁, D₂}` triple with D₁, D₂ diagonal
reaches `smGen 1`. Tier T3 (proved).
-/

/-- UJ is supported exactly on the partner anti-diagonal. Tier T3 (proved). -/
theorem UJ_support_iff (i j : I32) : UJ i j ≠ 0 ↔ j = partner i := by
  rw [UJ_apply]
  unfold UJ_matrix
  constructor
  · intro h
    by_contra hcon
    apply h
    rw [if_neg hcon]
  · intro h
    rw [if_pos h]
    exact one_ne_zero

/-- UJ satisfies the pair-support hypothesis. Tier T3 (proved). -/
theorem UJ_pairSupport (i j : I32) (h : UJ i j ≠ 0) : i = j ∨ j = partner i :=
  Or.inr ((UJ_support_iff i j).mp h)

/-- A diagonal-support matrix satisfies the pair-support hypothesis.
    Tier T3 (proved). -/
theorem diag_pairSupport (D : Matrix I32 I32 ℂ) (hD : ∀ i j : I32, D i j ≠ 0 → i = j)
    (i j : I32) (h : D i j ≠ 0) : i = j ∨ j = partner i :=
  Or.inl (hD i j h)

/-- The product `a * bᴴ` of pair-supported matrices vanishes off pair support.
    Tier T3 (proved). -/
theorem pairSupport_mul_star {a b : Matrix I32 I32 ℂ}
    (ha : ∀ i j : I32, a i j ≠ 0 → i = j ∨ j = partner i)
    (hb : ∀ i j : I32, b i j ≠ 0 → i = j ∨ j = partner i)
    (i k : I32) (hik : i ≠ k) (hkp : k ≠ partner i) :
    (a * b.conjTranspose) i k = 0 := by
  rw [Matrix.mul_apply]
  apply Finset.sum_eq_zero
  intro l _
  by_cases hal : a i l = 0
  · rw [hal, zero_mul]
  · have hbkl : b k l = 0 := by
      by_contra hne
      have h2 := hb k l hne
      have h1 := ha i l hal
      rcases h1 with rfl | hlp
      · rcases h2 with hkl | hlk
        · exact hik hkl.symm
        · apply hkp
          have hpi : partner i = k := by rw [hlk, partner_involutive]
          exact hpi.symm
      · rcases h2 with hkl | hpp
        · exact hkp (hkl.trans hlp)
        · exact hik (partner_injective (hlp.symm.trans hpp))
    have hstar : (b.conjTranspose) l k = star (b k l) := rfl
    rw [hstar, hbkl, star_zero, mul_zero]

/-- Ternary products preserve pair support. Tier T3 (proved). -/
theorem pairSupport_ternary {a b c : Matrix I32 I32 ℂ}
    (ha : ∀ i j : I32, a i j ≠ 0 → i = j ∨ j = partner i)
    (hb : ∀ i j : I32, b i j ≠ 0 → i = j ∨ j = partner i)
    (hc : ∀ i j : I32, c i j ≠ 0 → i = j ∨ j = partner i)
    (i j : I32) (hij : i ≠ j) (hjp : j ≠ partner i) :
    (ternaryMat a b c) i j = 0 := by
  unfold ternaryMat
  rw [Matrix.mul_apply]
  apply Finset.sum_eq_zero
  intro k _
  by_cases hckj : c k j = 0
  · rw [hckj, mul_zero]
  · have hsup := hc k j hckj
    rcases hsup with hkj | hjk
    · rw [hkj, pairSupport_mul_star ha hb i j hij hjp, zero_mul]
    · have hkj : k = partner j := by
        have h1 : partner j = partner (partner k) := congrArg partner hjk
        rw [partner_involutive] at h1
        exact h1.symm
      rw [hkj]
      have h1 : i ≠ partner j := by
        intro hcon
        apply hjp
        have h2 : partner i = j := by rw [hcon, partner_involutive]
        exact h2.symm
      have h2 : partner j ≠ partner i := by
        intro hcon
        exact hij (partner_injective hcon).symm
      rw [pairSupport_mul_star ha hb i (partner j) h1 h2, zero_mul]

/-- The TRO generated by pair-supported matrices contains only pair-supported
    matrices. Tier T3 (proved). -/
theorem memGenTRO_pairSupport {X Y Z : Matrix I32 I32 ℂ}
    (hX : ∀ i j : I32, X i j ≠ 0 → i = j ∨ j = partner i)
    (hY : ∀ i j : I32, Y i j ≠ 0 → i = j ∨ j = partner i)
    (hZ : ∀ i j : I32, Z i j ≠ 0 → i = j ∨ j = partner i)
    {M : Matrix I32 I32 ℂ} (hM : MemGenTRO ({X, Y, Z} : Set (Matrix I32 I32 ℂ)) M) :
    ∀ i j : I32, M i j ≠ 0 → i = j ∨ j = partner i := by
  induction hM with
  | of_mem a ha =>
    intro i j hne
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
    rcases ha with rfl | rfl | rfl
    · exact hX i j hne
    · exact hY i j hne
    · exact hZ i j hne
  | of_ternary a b c _ _ _ iha ihb ihc =>
    intro i j hne
    by_contra hcon
    push_neg at hcon
    obtain ⟨h1, h2⟩ := hcon
    exact hne (pairSupport_ternary iha ihb ihc i j h1 h2)

/-- R4: no `{UJ, D₁, D₂}` triple with D₁, D₂ diagonal reaches `smGen 1`.
    Kills the §7 target families `{UJ, genC, cfMat}` and `{UJ, gammaF, genC}`.
    Tier T3 (proved). -/
theorem no_UJ_diagonal_pair_reach (D₁ D₂ : Matrix I32 I32 ℂ)
    (hD₁ : ∀ i j : I32, D₁ i j ≠ 0 → i = j)
    (hD₂ : ∀ i j : I32, D₂ i j ≠ 0 → i = j) :
    ¬ MemGenTRO ({UJ, D₁, D₂} : Set (Matrix I32 I32 ℂ)) (smGen 1) := by
  intro hM
  have hmem := memGenTRO_pairSupport UJ_pairSupport (diag_pairSupport D₁ hD₁)
    (diag_pairSupport D₂ hD₂) hM
  have h01 : smGen (1 : Fin 12) (⟨0, by norm_num⟩ : I32)
      (⟨1, by norm_num⟩ : I32) ≠ 0 := by
    rw [smGen_one_offdiag]
    exact one_ne_zero
  have hsup := hmem _ _ h01
  rcases hsup with hcon | hcon
  · exact absurd hcon (by decide)
  · exact absurd hcon (by decide)

/-! ## §14. R5 — Entry-ring invariant: Gaussian integers cannot reach genM 7

The natural ingredient pool (UJ, γ_F, genC, cfMat, 1, and the genH/genM
families except genM 7) is visibly `ℤ[i]`-valued — but `genM 7` is not: the
Gell-Mann `λ₈` carries `1/√3`. The invariant: Gaussian-integer entries are
preserved by `star` (`gaussInt_star`), addition (`gaussInt_add`), and
multiplication (`gaussInt_mul`), hence by matrix multiplication
(`gaussInt_matrix_mul`) and ternary products (`gaussInt_ternary`), hence by
the whole generated TRO (`memGenTRO_gaussInt`). Since `genM 7` has the entry
`1/√3` at (18, 18) (`genM_seven_18_18`) and `1/√3` is not a Gaussian integer
(`not_gaussInt_inv_sqrt3`), `no_gaussInt_triple_reaches_genM7`: NO triple of
Gaussian-integer-entry matrices generates all twelve `smGen` — it provably
misses `smGen 11 = genM 7`. This is rubric rule R5, and it is the strongest
no-go yet: it kills every `ℤ[i]`-valued candidate family at once.
Tier T3 (proved).
-/

/-- A complex number is a Gaussian integer. Tier T2. -/
def IsGaussInt (z : ℂ) : Prop := ∃ a b : ℤ, z = (a : ℂ) + (b : ℂ) * Complex.I

theorem gaussInt_zero : IsGaussInt 0 := ⟨0, 0, by simp⟩
theorem gaussInt_one : IsGaussInt 1 := ⟨1, 0, by simp⟩

theorem gaussInt_add {x y : ℂ} (hx : IsGaussInt x) (hy : IsGaussInt y) :
    IsGaussInt (x + y) := by
  obtain ⟨a1, b1, rfl⟩ := hx
  obtain ⟨a2, b2, rfl⟩ := hy
  refine ⟨a1 + a2, b1 + b2, ?_⟩
  push_cast
  ring

theorem gaussInt_mul {x y : ℂ} (hx : IsGaussInt x) (hy : IsGaussInt y) :
    IsGaussInt (x * y) := by
  obtain ⟨a1, b1, rfl⟩ := hx
  obtain ⟨a2, b2, rfl⟩ := hy
  refine ⟨a1 * a2 - b1 * b2, a1 * b2 + b1 * a2, ?_⟩
  push_cast
  linear_combination ((b1 : ℂ) * (b2 : ℂ)) * Complex.I_mul_I

theorem gaussInt_star {z : ℂ} (hz : IsGaussInt z) : IsGaussInt (star z) := by
  obtain ⟨a, b, rfl⟩ := hz
  refine ⟨a, -b, ?_⟩
  push_cast
  simp

theorem gaussInt_sum {ι : Type*} [DecidableEq ι] (s : Finset ι) (f : ι → ℂ)
    (hf : ∀ k ∈ s, IsGaussInt (f k)) : IsGaussInt (∑ k ∈ s, f k) := by
  induction s using Finset.induction with
  | empty => simpa using gaussInt_zero
  | insert a s has ih =>
    rw [Finset.sum_insert has]
    exact gaussInt_add (hf a (Finset.mem_insert_self a s))
      (ih (fun k hk => hf k (Finset.mem_insert_of_mem hk)))

theorem gaussInt_matrix_mul {M N : Matrix I32 I32 ℂ}
    (hM : ∀ i j, IsGaussInt (M i j)) (hN : ∀ i j, IsGaussInt (N i j))
    (i j : I32) : IsGaussInt ((M * N) i j) := by
  rw [Matrix.mul_apply]
  exact gaussInt_sum _ _ (fun k _ => gaussInt_mul (hM i k) (hN k j))

theorem gaussInt_matrix_star {M : Matrix I32 I32 ℂ}
    (hM : ∀ i j, IsGaussInt (M i j)) (i j : I32) :
    IsGaussInt ((M.conjTranspose) i j) := by
  have hstar : (M.conjTranspose) i j = star (M j i) := rfl
  rw [hstar]
  exact gaussInt_star (hM j i)

theorem gaussInt_ternary {a b c : Matrix I32 I32 ℂ}
    (ha : ∀ i j, IsGaussInt (a i j))
    (hb : ∀ i j, IsGaussInt (b i j))
    (hc : ∀ i j, IsGaussInt (c i j))
    (i j : I32) : IsGaussInt ((ternaryMat a b c) i j) := by
  unfold ternaryMat
  have hab : ∀ i' j', IsGaussInt ((a * b.conjTranspose) i' j') := fun i' j' =>
    gaussInt_matrix_mul ha (fun i'' j'' => gaussInt_matrix_star hb i'' j'') i' j'
  exact gaussInt_matrix_mul hab hc i j

theorem memGenTRO_gaussInt {X Y Z : Matrix I32 I32 ℂ}
    (hX : ∀ i j, IsGaussInt (X i j))
    (hY : ∀ i j, IsGaussInt (Y i j))
    (hZ : ∀ i j, IsGaussInt (Z i j))
    {M : Matrix I32 I32 ℂ} (hM : MemGenTRO ({X, Y, Z} : Set (Matrix I32 I32 ℂ)) M) :
    ∀ i j : I32, IsGaussInt (M i j) := by
  induction hM with
  | of_mem a ha =>
    intro i j
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
    rcases ha with rfl | rfl | rfl
    · exact hX i j
    · exact hY i j
    · exact hZ i j
  | of_ternary a b c _ _ _ iha ihb ihc =>
    intro i j
    exact gaussInt_ternary iha ihb ihc i j

/-- `genM 7` has the entry `1/√3` at (18, 18). Tier T3 (proved). -/
theorem genM_seven_18_18 :
    genM 7 (⟨18, by norm_num⟩ : I32) (⟨18, by norm_num⟩ : I32) =
    (((Real.sqrt 3 : ℝ) : ℂ))⁻¹ := by
  have h : genM (7 : Fin 8) (⟨18, by norm_num⟩ : I32) (⟨18, by norm_num⟩ : I32)
      = ((Real.sqrt 3 : ℂ))⁻¹ * 1 := rfl
  rw [h, mul_one]

/-- A real Gaussian-integer equation forces the imaginary coefficient to
    vanish. Tier T3 (proved). -/
theorem gaussInt_real_im {r : ℝ} {a b : ℤ}
    (h : ((r : ℂ)) = ((a : ℤ) : ℂ) + ((b : ℤ) : ℂ) * Complex.I) : b = 0 := by
  have h_im := congrArg Complex.im h
  simp at h_im
  have h2 : (b : ℝ) = 0 := by linarith
  exact_mod_cast h2

/-- `1/√3` is not a Gaussian integer. Tier T3 (proved). -/
theorem not_gaussInt_inv_sqrt3 : ¬ IsGaussInt (((Real.sqrt 3 : ℝ) : ℂ)⁻¹) := by
  rintro ⟨a, b, hab⟩
  rw [← Complex.ofReal_inv] at hab
  -- hab : ((√3⁻¹:ℝ):ℂ) = ↑a + ↑b * I
  have hb0 : b = 0 := gaussInt_real_im hab
  subst hb0
  simp only [Int.cast_zero, zero_mul, add_zero] at hab
  -- hab : ((√3⁻¹:ℝ):ℂ) = ((a:ℤ):ℂ)
  have hab2 : ((((Real.sqrt 3)⁻¹ : ℝ)) : ℂ) = ((((a : ℤ) : ℝ)) : ℂ) := by
    calc ((((Real.sqrt 3)⁻¹ : ℝ)) : ℂ) = ((a : ℤ) : ℂ) := hab
      _ = ((((a : ℤ) : ℝ)) : ℂ) := by norm_cast
  have h_real : (Real.sqrt 3)⁻¹ = ((a : ℤ) : ℝ) := Complex.ofReal_injective hab2
  have h_sqrt_ne : (Real.sqrt 3 : ℝ) ≠ 0 := Real.sqrt_ne_zero'.mpr (by norm_num)
  have h_mul : ((a : ℤ) : ℝ) * Real.sqrt 3 = 1 := by
    have h2 := congrArg (fun x : ℝ => x * Real.sqrt 3) h_real
    rw [inv_mul_cancel₀ h_sqrt_ne] at h2
    exact h2.symm
  have h_sq : ((a : ℤ) : ℝ) ^ 2 * 3 = 1 := by
    have h2 := congrArg (fun x : ℝ => x ^ 2) h_mul
    rw [mul_pow, Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 3)] at h2
    simpa using h2
  have h_int : a ^ 2 * 3 = (1 : ℤ) := by
    have h3 : ((((a ^ 2 * 3 : ℤ))) : ℝ) = ((((1 : ℤ))) : ℝ) := by
      push_cast
      exact h_sq
    exact_mod_cast h3
  have h_dvd : (3 : ℤ) ∣ 1 := ⟨a ^ 2, by rw [mul_comm]; exact h_int.symm⟩
  exact absurd h_dvd (by norm_num)

/-- R5: no triple of Gaussian-integer-entry matrices reaches `smGen 11`.
    Tier T3 (proved). -/
theorem no_gaussInt_triple_reaches_genM7 (X Y Z : Matrix I32 I32 ℂ)
    (hX : ∀ i j, IsGaussInt (X i j))
    (hY : ∀ i j, IsGaussInt (Y i j))
    (hZ : ∀ i j, IsGaussInt (Z i j)) :
    ¬ MemGenTRO ({X, Y, Z} : Set (Matrix I32 I32 ℂ)) (smGen 11) := by
  intro hM
  have hmem := memGenTRO_gaussInt hX hY hZ hM
  have h11 : smGen (11 : Fin 12) = genM 7 := rfl
  have h_entry := hmem (⟨18, by norm_num⟩ : I32) (⟨18, by norm_num⟩ : I32)
  rw [h11, genM_seven_18_18] at h_entry
  exact not_gaussInt_inv_sqrt3 h_entry

/-! ## §15. Positive reachability: the rubric's remaining window

The §7 target (a) families `{UJ, genC, cfMat}` and `{UJ, gammaF, genC}` are
R4-dead for `smGen 1` (`no_UJ_diagonal_pair_reach`) — a proved obstruction,
not a failure of effort. What the rubric leaves alive: a triple containing
UJ *and* a non-diagonal, non-pair-support tripotent could break pair
support. Concretely, the next positive step is to prove `Tripotent (genH k)`
or `Tripotent (genM a)` and test mixed triples like `{genH 0, UJ, genM 0}`.

As a sanity check, the valid tripotent triple `{genC, UJ, gammaF}` (all three
proved: `tripotent_genC`, `tripotent_UJ`, `tripotent_gammaF`) reaches
`smGen 0 = genC` by membership — but is R4-dead for `smGen 1`, since `genC`
and `gammaF` are diagonal (`genC_eq_diagonal`, `gammaF_eq_diagonal`).
Partial reachability, honestly separated into proved lemmas. Tier T3.
-/

/-- The tripotent triple `{genC, UJ, gammaF}` reaches `smGen 0`.
    Tier T3 (proved). -/
theorem triple_genC_UJ_gammaF_reaches_smGen0 :
    MemGenTRO ({genC, UJ, gammaF} : Set (Matrix I32 I32 ℂ)) (smGen 0) := by
  have h0 : smGen (0 : Fin 12) = genC := rfl
  rw [h0]
  exact MemGenTRO.of_mem _ (by simp)

/-- ...but it cannot reach `smGen 1` (R4). Tier T3 (proved). -/
theorem triple_genC_UJ_gammaF_cannot_reach_smGen1 :
    ¬ MemGenTRO ({genC, UJ, gammaF} : Set (Matrix I32 I32 ℂ)) (smGen 1) := by
  have hset : ({genC, UJ, gammaF} : Set (Matrix I32 I32 ℂ)) = {UJ, genC, gammaF} :=
    Set.insert_comm genC UJ {gammaF}
  rw [hset]
  apply no_UJ_diagonal_pair_reach
  · intro i j h
    by_contra hcon
    apply h
    rw [genC_eq_diagonal, Matrix.diagonal_apply_ne _ hcon]
  · intro i j h
    by_contra hcon
    apply h
    rw [gammaF_eq_diagonal, Matrix.diagonal_apply_ne _ hcon]

/-! ## §16. Final push: H/M-sector tripotents and the mixed triple

Fourth wave (2026-09-28). The rubric's remaining window (§15): a triple with
UJ and a non-diagonal, non-pair-support tripotent. The H-sector generators
`genH k` (Pauli doublets) and the M-sector generator `genM 0` (Gell-Mann λ₀
triplet) are exactly such tripotents — proved here via a uniform
Hermitian-square-projector lemma (`tripotent_of_hermitian_sq_proj`).

New inventory: `tripotent_genH` (all three), `tripotent_genM0`.
New kill: `not_tripotent_genM7` — the one generator with irrational entries
is NOT a tripotent (diagonal, but |1/√3| ∉ {0, 1}), closing the "irrational
tripotent inside the natural pool" escape from R5.

Positive: the valid tripotent triple `{genH 0, UJ, genM 0}` reaches `smGen 1`
and `smGen 4` by membership (`triple_genH0_UJ_genM0_reaches_1_4`) — the first
triple to reach an off-diagonal generator — and the H-sector triple reaches
`smGen 1, 2, 3` (`triple_genH_reaches_123`). But the mixed triple provably
misses `smGen 11` by R5 (`triple_genH0_UJ_genM0_misses_11`): all three are
ℤ[i]-valued. Tier T3 (proved throughout).
-/

/-- Hermitian matrices whose square is a 0/1 support projector are tripotents:
    {{e,e,e}} = e·eᴴ·e = e³ = (e²)·e = P·e = e, since e is supported where
    P = 1. Tier T3 (proved). -/
theorem tripotent_of_hermitian_sq_proj {e : Matrix I32 I32 ℂ} {P : I32 → ℂ}
    (hH : e.conjTranspose = e)
    (hsq : e * e = Matrix.diagonal P)
    (hsupp : ∀ i j, e i j ≠ 0 → P i = 1) :
    Tripotent e := by
  unfold Tripotent ternaryMat
  rw [hH, hsq]
  ext i j
  have hentry : (Matrix.diagonal P * e) i j = P i * e i j := by
    rw [Matrix.mul_apply, Finset.sum_eq_single i]
    · rw [Matrix.diagonal_apply_eq]
    · intro k _ hki
      rw [Matrix.diagonal_apply_ne _ (Ne.symm hki), zero_mul]
    · intro hcon
      exact absurd (Finset.mem_univ i) hcon
  rw [hentry]
  by_cases he : e i j = 0
  · rw [he, mul_zero]
  · rw [hsupp i j he, one_mul]

/-- Pauli matrices are Hermitian. Tier T3 (proved). -/
theorem pauli_herm (k : Fin 3) : (pauli k).conjTranspose = pauli k := by
  fin_cases k <;> ext p q <;> fin_cases p <;> fin_cases q <;>
    simp [Matrix.conjTranspose_apply, pauli]

/-- genH k is self-adjoint. Tier T3 (proved). -/
theorem genH_herm (k : Fin 3) : (genH k).conjTranspose = genH k := by
  ext i j
  rw [Matrix.conjTranspose_apply]
  unfold genH
  simp only
  split_ifs with h1 h2 h2
  · have hh0 := congrFun (congrFun (pauli_herm k)
      ⟨j.val % 2, Nat.mod_lt _ (by norm_num)⟩)
      ⟨i.val % 2, Nat.mod_lt _ (by norm_num)⟩
    rw [Matrix.conjTranspose_apply] at hh0
    rw [← hh0, star_star]
  · exfalso
    obtain ⟨hj8, hi8, hdiv⟩ := h1
    exact h2 ⟨hi8, hj8, hdiv.symm⟩
  · exfalso
    obtain ⟨hi8, hj8, hdiv⟩ := h2
    exact h1 ⟨hj8, hi8, hdiv.symm⟩
  · exact star_zero _

/-- (genH k)² is the diagonal support projector. Tier T3 (proved). -/
theorem genH_sq_diag (k : Fin 3) :
    genH k * genH k = Matrix.diagonal fun i => if i.val < 8 then (1:ℂ) else 0 := by
  ext i j
  by_cases hij : i = j
  · subst hij
    rw [genH_sq_proj k i, Matrix.diagonal_apply_eq]
  · rw [genH_sq_offdiag k hij, Matrix.diagonal_apply_ne _ hij]

/-- The H-sector generators are tripotents. Tier T3 (proved). -/
theorem tripotent_genH (k : Fin 3) : Tripotent (genH k) := by
  refine tripotent_of_hermitian_sq_proj (genH_herm k) (genH_sq_diag k) ?_
  · intro i j hne
    have h8 : i.val < 8 := (genH_supp_block k i j hne).1
    show (if i.val < 8 then (1:ℂ) else 0) = 1
    rw [if_pos h8]

/-- (gellMann 0)² is the diagonal 0/1 projector. Tier T3 (proved). -/
theorem gellMann_zero_sq :
    gellMann 0 * gellMann 0 = Matrix.diagonal ![1, 1, 0] := by
  ext p q
  fin_cases p <;> fin_cases q <;>
    simp [gellMann, Matrix.mul_apply, Fin.sum_univ_three, Matrix.diagonal_apply] <;>
    norm_num

/-- Diagonal entries of (gellMann 0)² are 0 or 1. Tier T3 (proved). -/
theorem gellMann_zero_sq_diag01 (p : Fin 3) :
    (gellMann 0 * gellMann 0) p p = 1 ∨ (gellMann 0 * gellMann 0) p p = 0 := by
  rw [gellMann_zero_sq, Matrix.diagonal_apply_eq]
  fin_cases p <;> simp

/-- Nonzero entries of gellMann 0 sit where (gellMann 0)² is 1 on the
    diagonal. Tier T3 (proved). -/
theorem gellMann_zero_sq_of_ne (p q : Fin 3) (h : gellMann 0 p q ≠ 0) :
    (gellMann 0 * gellMann 0) p p = 1 := by
  rw [gellMann_zero_sq, Matrix.diagonal_apply_eq]
  fin_cases p <;> fin_cases q <;> simp [gellMann] at h ⊢

/-- Support projector for (genM 0)². Tier T2. -/
noncomputable def genM0supp : I32 → ℂ := fun i =>
  match tripletOf i.val with
  | some (_, p) => (gellMann 0 * gellMann 0) p p
  | none => 0

theorem genM0supp_eq (i : I32) (t : Fin 4) (p : Fin 3)
    (h : tripletOf i.val = some (t, p)) :
    genM0supp i = (gellMann 0 * gellMann 0) p p := by
  unfold genM0supp
  rw [h]

theorem genM0supp_none (i : I32) (h : tripletOf i.val = none) :
    genM0supp i = 0 := by
  unfold genM0supp
  rw [h]

/-- (genM 0)² is the diagonal triplet-support projector. Tier T3 (proved). -/
theorem genM_zero_sq_diag : genM 0 * genM 0 = Matrix.diagonal genM0supp := by
  ext i j
  by_cases h : ∃ t : Fin 4, ∃ p q : Fin 3,
      tripletOf i.val = some (t, p) ∧ tripletOf j.val = some (t, q)
  · obtain ⟨t, p, q, hi, hj⟩ := h
    rw [genM_sq_onblock 0 i j t p q hi hj]
    by_cases hij : i = j
    · subst hij
      have hpq : p = q := congrArg Prod.snd (Option.some_inj.mp (hi.symm.trans hj))
      subst hpq
      rw [Matrix.diagonal_apply_eq, genM0supp_eq i t p hi]
    · have h0 : (gellMann 0 * gellMann 0) p q = 0 := by
        by_cases hpq : p = q
        · subst hpq
          have hii : i = tripletIdx t p := tripletOf_inv i t p hi
          have hjj : j = tripletIdx t p := tripletOf_inv j t p hj
          exact absurd (hii.trans hjj.symm) hij
        · rw [gellMann_zero_sq, Matrix.diagonal_apply_ne _ hpq]
      rw [h0, Matrix.diagonal_apply_ne _ hij]
  · have hLHS : (genM 0 * genM 0) i j = 0 := by
      rw [Matrix.mul_apply]
      apply Finset.sum_eq_zero
      intro l _
      by_cases g1 : genM 0 i l = 0
      · rw [g1, zero_mul]
      · by_cases g2 : genM 0 l j = 0
        · rw [g2, mul_zero]
        · exfalso
          obtain ⟨t1, p1, q1, h1i, h1l⟩ := genM_supp_triplet 0 i l g1
          obtain ⟨t2, p2, q2, h2l, h2j⟩ := genM_supp_triplet 0 l j g2
          have htt : t1 = t2 :=
            congrArg Prod.fst (Option.some_inj.mp (h1l.symm.trans h2l))
          subst htt
          exact h ⟨t1, p1, q2, h1i, h2j⟩
    rw [hLHS]
    by_cases hij : i = j
    · subst hij
      have hnone : tripletOf i.val = none := by
        cases hto : tripletOf i.val with
        | none => rfl
        | some tp =>
          obtain ⟨t, p⟩ := tp
          exact absurd ⟨t, p, p, hto, hto⟩ h
      rw [Matrix.diagonal_apply_eq, genM0supp_none i hnone]
    · rw [Matrix.diagonal_apply_ne _ hij]

/-- The M-sector generator genM 0 is a tripotent. Tier T3 (proved). -/
theorem tripotent_genM0 : Tripotent (genM 0) := by
  refine tripotent_of_hermitian_sq_proj (genM_herm 0) (genM_zero_sq_diag) ?_
  · intro i j hne
    obtain ⟨t, p, q, hi, hj⟩ := genM_supp_triplet 0 i j hne
    rw [genM0supp_eq i t p hi]
    have h2 : genM 0 i j = gellMann 0 p q := genM_apply_eq 0 i j t p q hi hj
    rw [h2] at hne
    exact gellMann_zero_sq_of_ne p q hne

/-- genM 7 is diagonal (λ₇ is diagonal). Tier T3 (proved). -/
theorem genM_seven_diagonal (i j : I32) (h : genM 7 i j ≠ 0) : i = j := by
  obtain ⟨t, p, q, hi, hj⟩ := genM_supp_triplet 7 i j h
  have h2 : gellMann 7 p q ≠ 0 := by
    have h3 := genM_apply_eq 7 i j t p q hi hj
    rwa [h3] at h
  have hpq : p = q := by
    fin_cases p <;> fin_cases q <;> simp [gellMann] at h2 ⊢
  subst hpq
  have hii : i = tripletIdx t p := tripletOf_inv i t p hi
  have hjj : j = tripletIdx t p := tripletOf_inv j t p hj
  exact hii.trans hjj.symm

/-- Diagonal form of genM 7. Tier T3 (proved). -/
theorem genM_seven_diag_form :
    genM 7 = Matrix.diagonal fun i => genM 7 i i := by
  ext i j
  by_cases h : i = j
  · subst h; rw [Matrix.diagonal_apply_eq]
  · rw [Matrix.diagonal_apply_ne _ h]
    by_contra hne
    exact h (genM_seven_diagonal i j hne)

/-- genM 7 is NOT a tripotent: it is diagonal with the entry 1/√3 at (18,18),
    but |1/√3| ∉ {0, 1}, so the scalar tripotent equation fails there.
    This closes the "irrational tripotent inside the natural pool" escape
    from R5. Tier T3 (proved). -/
theorem not_tripotent_genM7 : ¬ Tripotent (genM 7) := by
  intro htri
  unfold Tripotent at htri
  rw [genM_seven_diag_form, ternaryMat_diagonal] at htri
  have h18 := congrFun (congrFun htri ⟨18, by norm_num⟩) ⟨18, by norm_num⟩
  rw [Matrix.diagonal_apply_eq, Matrix.diagonal_apply_eq] at h18
  rw [genM_seven_18_18] at h18
  have hsqrt : (Real.sqrt 3 : ℝ) ≠ 0 := Real.sqrt_ne_zero'.mpr (by norm_num)
  have hx : ((((Real.sqrt 3 : ℝ) : ℂ))) ≠ 0 := by exact_mod_cast hsqrt
  have hne : ((((Real.sqrt 3 : ℝ) : ℂ))⁻¹) ≠ 0 := inv_ne_zero hx
  have hstar : star ((((Real.sqrt 3 : ℝ) : ℂ))⁻¹) = ((((Real.sqrt 3 : ℝ) : ℂ))⁻¹) := by
    rw [← Complex.ofReal_inv]
    simp
  rw [hstar] at h18
  have hsq1 : ((((Real.sqrt 3 : ℝ) : ℂ))⁻¹) * ((((Real.sqrt 3 : ℝ) : ℂ))⁻¹) = 1 :=
    mul_right_cancel₀ hne (by rw [one_mul]; exact h18)
  have hxx : ((((Real.sqrt 3 : ℝ) : ℂ))) * ((((Real.sqrt 3 : ℝ) : ℂ))) = 1 := by
    have h2 := congrArg (fun z : ℂ => z⁻¹) hsq1
    rwa [mul_inv_rev, inv_inv, inv_one] at h2
  have h3 : ((((Real.sqrt 3 : ℝ) : ℂ))) * ((((Real.sqrt 3 : ℝ) : ℂ))) = 3 := by
    have hsq : (Real.sqrt 3) ^ 2 = 3 := Real.sq_sqrt (by norm_num)
    have hcc : ((((Real.sqrt 3 : ℝ) : ℂ))) * ((((Real.sqrt 3 : ℝ) : ℂ)))
        = ((((Real.sqrt 3) ^ 2 : ℝ)) : ℂ) := by push_cast; ring
    rw [hcc, hsq]
    norm_num
  rw [hxx] at h3
  norm_num at h3

/-- Gaussian-integer facts for the R5 ceiling. Tier T3 (proved). -/
theorem gaussInt_neg_one : IsGaussInt (-1) := ⟨-1, 0, by push_cast; ring⟩

theorem gaussInt_I : IsGaussInt Complex.I := ⟨0, 1, by push_cast; ring⟩

theorem gaussInt_neg_I : IsGaussInt (-Complex.I) := ⟨0, -1, by push_cast; ring⟩

theorem pauli_gaussInt (k : Fin 3) (a b : Fin 2) : IsGaussInt (pauli k a b) := by
  fin_cases k <;> fin_cases a <;> fin_cases b <;>
    simp only [pauli, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons] <;>
    first
      | exact gaussInt_zero
      | exact gaussInt_one
      | exact gaussInt_neg_one
      | exact gaussInt_I
      | exact gaussInt_neg_I

theorem genH_gaussInt (k : Fin 3) (i j : I32) : IsGaussInt (genH k i j) := by
  unfold genH
  simp only
  by_cases h : i.val < 8 ∧ j.val < 8 ∧ i.val / 2 = j.val / 2
  · rw [if_pos h]; exact pauli_gaussInt k _ _
  · rw [if_neg h]; exact gaussInt_zero

theorem gellMann_zero_gaussInt (p q : Fin 3) : IsGaussInt (gellMann 0 p q) := by
  fin_cases p <;> fin_cases q <;>
    simp only [gellMann, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons] <;>
    first
      | exact gaussInt_zero
      | exact gaussInt_one
      | exact gaussInt_neg_one
      | exact gaussInt_I
      | exact gaussInt_neg_I

theorem genM_zero_gaussInt (i j : I32) : IsGaussInt (genM 0 i j) := by
  unfold genM
  cases h1 : tripletOf i.val with
  | none =>
    cases h2 : tripletOf j.val with
    | none => simp only [gaussInt_zero]
    | some tp2 => simp only [gaussInt_zero]
  | some tp1 =>
    obtain ⟨t1, p1⟩ := tp1
    cases h2 : tripletOf j.val with
    | none => simp only [gaussInt_zero]
    | some tp2 =>
      obtain ⟨t2, p2⟩ := tp2
      simp only []
      by_cases heq : t1 = t2
      · rw [if_pos heq]; exact gellMann_zero_gaussInt p1 p2
      · rw [if_neg heq]; exact gaussInt_zero

theorem UJ_gaussInt (i j : I32) : IsGaussInt (UJ i j) := by
  have hUJ : UJ i j = (if j = partner i then (1:ℂ) else 0) := by
    rw [UJ_apply]; rfl
  rw [hUJ]
  by_cases h : j = partner i <;> simp [h, gaussInt_one, gaussInt_zero]

/-- The mixed triple reaches `smGen 1` and `smGen 4` by membership — the first
    triple to reach an off-diagonal generator. Tier T3 (proved). -/
theorem triple_genH0_UJ_genM0_reaches_1_4 :
    MemGenTRO ({genH 0, UJ, genM 0} : Set (Matrix I32 I32 ℂ)) (smGen 1) ∧
    MemGenTRO ({genH 0, UJ, genM 0} : Set (Matrix I32 I32 ℂ)) (smGen 4) := by
  have h1 : smGen (1 : Fin 12) = genH 0 := rfl
  have h4 : smGen (4 : Fin 12) = genM 0 := rfl
  exact ⟨by rw [h1]; exact MemGenTRO.of_mem _ (by simp),
         by rw [h4]; exact MemGenTRO.of_mem _ (by simp)⟩

/-- ...but it provably misses `smGen 11` by R5: all three are ℤ[i]-valued.
    Tier T3 (proved). -/
theorem triple_genH0_UJ_genM0_misses_11 :
    ¬ MemGenTRO ({genH 0, UJ, genM 0} : Set (Matrix I32 I32 ℂ)) (smGen 11) :=
  no_gaussInt_triple_reaches_genM7 (genH 0) UJ (genM 0)
    (fun i j => genH_gaussInt 0 i j)
    (fun i j => UJ_gaussInt i j)
    (fun i j => genM_zero_gaussInt i j)

/-- The H-sector triple reaches `smGen 1, 2, 3` by membership. Tier T3. -/
theorem triple_genH_reaches_123 :
    MemGenTRO ({genH 0, genH 1, genH 2} : Set (Matrix I32 I32 ℂ)) (smGen 1) ∧
    MemGenTRO ({genH 0, genH 1, genH 2} : Set (Matrix I32 I32 ℂ)) (smGen 2) ∧
    MemGenTRO ({genH 0, genH 1, genH 2} : Set (Matrix I32 I32 ℂ)) (smGen 3) := by
  have h1 : smGen (1 : Fin 12) = genH 0 := rfl
  have h2 : smGen (2 : Fin 12) = genH 1 := rfl
  have h3 : smGen (3 : Fin 12) = genH 2 := rfl
  exact ⟨by rw [h1]; exact MemGenTRO.of_mem _ (by simp),
         by rw [h2]; exact MemGenTRO.of_mem _ (by simp),
         by rw [h3]; exact MemGenTRO.of_mem _ (by simp)⟩

end ThetLogos
