"""Attack 3: axiom ablation for Q3 (LOCAL ONLY, no Lean changes, no commits).

For each of the 6,494 candidate finite real *-algebras (same catalogue and
canonical probes as Attacks 1-2), measure the selective power of Connes-style
axioms, applied cumulatively:

  baseline      order-zero + order-one (asymmetric probe)          [Attacks 1-2]
  +irreducibility  commutant of {pi, pi^circ, D, J_F, Gamma_F} == C*I_32
  +orientability   Gamma_F in *-algebra generated by pi(A), [D, pi(A)]
  (Poincare duality: CONTROL FAILS - intersection form vanishes identically
   under the repo's folded conventions; see report. Excluded from the chain.)
  KO signs recorded as controls (KO-dimension 6 table).

Conventions mirror common.py / dirac_scan.py. Deterministic (seeded) generic
D sampling from each algebra's admissible order-one nullspace. T4 numerical.

Usage:
  python3 -m thet_logos.axiom_scan --selftest
  python3 -m thet_logos.axiom_scan --controls
  python3 -m thet_logos.axiom_scan --scan   (full 6494 ablation, ~5 min, 2 workers)
"""

import numpy as np, json, time, hashlib, sys, os
from multiprocessing import Pool

from .common import UJ, gamma_F, piOp, pi as sm_pi, DF_oneGen, DIM, af_generators
from .algebra_scan import (catalogue, block_generators, irrep_dim, algebra_name,
                           real_dim)
from .dirac_scan import d_basis, NULL_TOL_REL, ce_corner_rank

SEED = 2026
TOL = 1e-8          # numerical zero for nullity / residuals
NWORKERS = 2

def DF_ref():
    """Reference one-generation Dirac (same Yukawas as dirac_scan calibration)."""
    return DF_oneGen(0.5, 0.7, 1.1, 0.9)

# ----------------------------------------------------------------------------
# First-block admissible-D nullspace (cached per first-block type)
# ----------------------------------------------------------------------------
_FB = {}

def fb_data(n, K):
    """(d, V_null (272,nul), nul) for the asymmetric probe of first block (n,K).

    V_null is a real orthonormal basis of the D-coefficient nullspace of the
    full order-one constraint system (same system as dirac_scan.general_nullity,
    but retaining the null vectors)."""
    key = (n, K)
    if key in _FB:
        return _FB[key]
    d = irrep_dim(n, K)
    gens = block_generators(n, K)
    Xm = []
    for Gg in gens:
        M = np.zeros((DIM, DIM), complex); M[:d, :d] = Gg; Xm.append(M)
    Ym = [piOp(M) for M in Xm]
    B = d_basis()
    R = None
    for X in Xm:
        BX = np.einsum('kij,jl->kil', B, X) - np.einsum('ij,kjl->kil', X, B)
        for Y in Ym:
            V = np.einsum('kij,jl->kil', BX, Y) - np.einsum('ij,kjl->kil', Y, BX)
            F = np.concatenate([V.real.reshape(272, -1),
                                V.imag.reshape(272, -1)], axis=1).T  # (2048,272)
            M_ = F if R is None else np.vstack([R, F])
            R = np.linalg.qr(M_, mode='r')
    _, s_, Vh = np.linalg.svd(R)
    smax = s_[0] if s_[0] > 0 else 1.0
    nul = int(np.sum(s_ <= NULL_TOL_REL * smax))
    out = dict(d=d, V_null=Vh[272 - nul:].T.copy(), nul=nul)
    _FB[key] = out
    return out


def sample_D(blocks, idx):
    """Seeded generic D from the algebra's admissible nullspace (real coeffs)."""
    n, K = blocks[0]
    fb = fb_data(n, K)
    h = hashlib.md5(repr(blocks).encode()).hexdigest()
    seed = (SEED ^ int(h[:8], 16) ^ (idx * 0x9E3779B1)) & 0xFFFFFFFF
    rng = np.random.default_rng(seed)
    z = rng.standard_normal(fb['nul'])
    c = fb['V_null'] @ z
    D = np.tensordot(c, d_basis(), axes=([0], [0]))
    return D


def _vr(M):
    return np.concatenate([M.real.ravel(), M.imag.ravel()])


# ----------------------------------------------------------------------------
# 1. Irreducibility: commutant of {pi, pi^circ, D, J, Gamma} (real-linear)
# ----------------------------------------------------------------------------
# Exact reduction: [X,pi_k]=[X,pi^circ_k]=0  <=>  X = diag(lam I_d, A, mu I_d, B)
# on blocks b1=[0,d), r1=[d,16), b2=[16,16+d), r2=[16+d,32).
# We precompute (per d) the nullspace of the D-independent J/Gamma constraints
# and work only in that reduced real space; per-sample we then impose [X,D]=0.
_IR = {}

def ir_setup(d):
    if d in _IR:
        return _IR[d]
    U, G = UJ(), gamma_F()
    E = []
    M = np.zeros((32, 32), complex); M[:d, :d] = np.eye(d); E.append(M.copy())
    M = np.zeros((32, 32), complex); M[:d, :d] = 1j * np.eye(d); E.append(M.copy())
    M = np.zeros((32, 32), complex); M[16:16 + d, 16:16 + d] = np.eye(d); E.append(M.copy())
    M = np.zeros((32, 32), complex); M[16:16 + d, 16:16 + d] = 1j * np.eye(d); E.append(M.copy())
    for p in range(d, 16):
        for q in range(d, 16):
            M = np.zeros((32, 32), complex); M[p, q] = 1.0; E.append(M.copy())
            M = np.zeros((32, 32), complex); M[p, q] = 1j; E.append(M.copy())
    for p in range(16 + d, 32):
        for q in range(16 + d, 32):
            M = np.zeros((32, 32), complex); M[p, q] = 1.0; E.append(M.copy())
            M = np.zeros((32, 32), complex); M[p, q] = 1j; E.append(M.copy())
    n_p = len(E)
    FJ = np.stack([_vr(Ej @ U - U @ Ej.conj()) for Ej in E]).T      # XU = U Xbar
    FG = np.stack([_vr(Ej @ G - G @ Ej) for Ej in E]).T             # [X,Gamma]=0
    _, s_, Vh = np.linalg.svd(np.vstack([FJ, FG]), full_matrices=False)
    smax = s_[0] if s_[0] > 0 else 1.0
    nul = int(np.sum(s_ <= TOL * smax))
    N = Vh[n_p - nul:].T.copy()  # (n_p, n_red): reduced real basis coeffs
    Eprime = [sum(N[k, j] * E[k] for k in range(n_p))
              for j in range(N.shape[1])]
    out = dict(Eprime=Eprime, n_red=N.shape[1], jg_nul=nul, n_p=n_p)
    _IR[d] = out
    return out


def irreducibility_nullity(d, D):
    """Real nullity of the full commutant {pi,pi^circ,D,J,Gamma} (reduced)."""
    st = ir_setup(d)
    F = np.stack([_vr(Ej @ D - D @ Ej) for Ej in st['Eprime']]).T
    s = np.linalg.svd(F, compute_uv=False)
    smax = s[0] if s[0] > 0 else 1.0
    return int(np.sum(s <= TOL * smax))


def d_independent_commutant_nullity(d):
    """Complex nullity of commutant(pi, pi^circ) alone: 2 + 2*(16-d)^2 (exact)."""
    return 2 + 2 * (16 - d) ** 2


# ----------------------------------------------------------------------------
# 2. Poincare duality: intersection form (CONTROL-LEVEL; see report)
# ----------------------------------------------------------------------------
def poincare_cap_literal(blocks):
    """Literal task formula with the folded sequential rep.

    Returns (Cap, absdet). Theorem (verified numerically): Cap = 0 identically
    for every sector-1-localized *-representation when J is the sector swap,
    because pi(p_i) and J pi(p_j) J^-1 have disjoint support. The doubled
    (pi(+)pi) variant also gives 0 by Gamma_+/Gamma_- cancellation.
    """
    offs, ds = [], []
    o = 0
    for (n, K) in blocks:
        d = irrep_dim(n, K)
        offs.append(o); ds.append(d); o += d
    nb = len(blocks)
    G = gamma_F()
    Cap = np.zeros((nb, nb))
    for i in range(nb):
        Pi = np.zeros((32, 32), complex)
        Pi[offs[i]:offs[i] + ds[i], offs[i]:offs[i] + ds[i]] = np.eye(ds[i])
        for j in range(nb):
            Pj = np.zeros((32, 32), complex)
            Pj[offs[j]:offs[j] + ds[j], offs[j]:offs[j] + ds[j]] = np.eye(ds[j])
            Qj = piOp(Pj)
            Cap[i, j] = np.trace(G @ Pi @ Qj).real
    return Cap, abs(np.linalg.det(Cap))


# ----------------------------------------------------------------------------
# 3. Orientability: Gamma in *-algebra generated by pi(A), [D, pi(A)]
#    Exact via bicommutant: Gamma in M  <=>  [Gamma, Y] = 0 for all Y in M',
#    M' = commutant of S = {pi_k} U {[D, pi_k]}.
#    Reduction (exact): [X, pi_k] = 0  =>  X = diag(lam I_d, X_r); only the
#    [X, [D,pi_k]] = 0 block equations remain (complex-linear, small).
# ----------------------------------------------------------------------------
def orientability(blocks, D):
    """Return (pass, residual). residual = max_j ||[Gamma, Y_j]||_F / ||Y_j||."""
    d = irrep_dim(*blocks[0])
    G = gamma_F()
    r = 32 - d
    rows = []
    for Gg in block_generators(*blocks[0]):
        Pk = np.zeros((32, 32), complex); Pk[:d, :d] = Gg
        W = D @ Pk - Pk @ D
        W12 = W[:d, d:]; W21 = W[d:, :d]
        # (1,2): lam*W12 - W12@Xr = 0 ; unknowns [lam, vec(Xr)]
        # vec(W12@Xr) = kron(I_r, W12) vec(Xr)
        rows.append(np.hstack([W12.reshape(-1, 1),
                               -np.kron(np.eye(r), W12)]))
        # (2,1): Xr@W21 - lam*W21 = 0
        rows.append(np.hstack([-W21.reshape(-1, 1),
                               np.kron(W21.T, np.eye(r))]))
    F = np.vstack(rows)
    U_, s_, Vh = np.linalg.svd(F, full_matrices=False)
    smax = s_[0] if s_[0] > 0 else 1.0
    nul = int(np.sum(s_ <= TOL * smax))
    worst = 0.0
    for j in range(nul):
        v = Vh[-(nul - j), :]
        lam = v[0]; Xr = v[1:].reshape(r, r)
        X = np.zeros((32, 32), complex)
        X[:d, :d] = lam * np.eye(d); X[d:, d:] = Xr
        nX = np.linalg.norm(X)
        if nX > 0:
            worst = max(worst, np.linalg.norm(G @ X - X @ G) / nX)
    return (worst < TOL), worst


# ----------------------------------------------------------------------------
# 4. KO signs (KO-dimension 6): J^2=+1, JD=+DJ, JGamma=-Gamma J
# ----------------------------------------------------------------------------
def ko_check(D=None):
    U, G = UJ(), gamma_F()
    out = {}
    out['J2_resid'] = float(np.max(np.abs(U @ U - np.eye(32))))       # J^2=+1 (U real)
    out['JG_resid'] = float(np.max(np.abs(U @ G @ U + G)))             # JGJ^-1 = -G
    B = d_basis()
    UB = np.einsum('ab,jbc,cd->jad', U, B.conj(), U)
    out['Dbasis_J_resid'] = float(np.max(np.abs(UB - B)))
    if D is not None:
        out['JD_resid'] = float(np.max(np.abs(U @ D.conj() @ U - D)))
    return out


# ----------------------------------------------------------------------------
# Efficient real-linear commutant nullity (Kronecker construction).
# X complex 32x32; x = [Re vec(X); Im vec(X)] in R^2048.
# ----------------------------------------------------------------------------
def commutant_nullity_real(M_list, D=None, use_J=False, use_Gamma=False):
    """Real nullity of {X : [X,M]=0 for M in M_list, [X,D]=0, XU=U Xbar,
    [X,Gamma]=0}."""
    U, G = UJ(), gamma_F()
    I = np.eye(32)
    rows = []
    for M in M_list:
        K = np.kron(M.T, I) - np.kron(I, M)
        Ar, Ai = K.real, K.imag
        rows.append(np.block([[Ar, -Ai], [Ai, Ar]]))
    if D is not None:
        K = np.kron(D.T, I) - np.kron(I, D)
        Ar, Ai = K.real, K.imag
        rows.append(np.block([[Ar, -Ai], [Ai, Ar]]))
    if use_Gamma:
        K = np.kron(G.T, I) - np.kron(I, G)
        Ar, Ai = K.real, K.imag
        rows.append(np.block([[Ar, -Ai], [Ai, Ar]]))
    if use_J:
        KU1 = np.kron(U, I)
        KU2 = np.kron(I, U)
        Z = np.zeros((1024, 1024))
        rows.append(np.block([[KU1 - KU2, Z], [Z, KU1 + KU2]]))
    F = np.vstack(rows)
    s = np.linalg.svd(F, compute_uv=False)
    smax = s[0] if s[0] > 0 else 1.0
    return int(np.sum(s <= TOL * smax))


# ----------------------------------------------------------------------------
# Controls (must pass before the scan means anything)
# ----------------------------------------------------------------------------
def control_irreducibility_SM():
    """Full real-linear commutant of the SM triple (common.pi, DF_oneGen).

    Staged (exact): first the complex-linear commutant of {pi_k}, then the
    remaining constraints in that reduced space."""
    gens = af_generators()
    Xm = [sm_pi(g) for g in gens]
    Ym = [piOp(M) for M in Xm]
    D = DF_ref()
    U, G = UJ(), gamma_F()
    I = np.eye(32)
    # Stage 1: complex-linear nullspace of [X, pi_k] = 0
    F1 = np.vstack([np.kron(M.T, I) - np.kron(I, M) for M in Xm])
    _, s1, Vh1 = np.linalg.svd(F1, full_matrices=False)
    r1 = int(np.sum(s1 <= TOL * (s1[0] if s1[0] > 0 else 1.0)))
    Np = Vh1[-r1:].T.copy()  # (1024, r1) complex
    Bm = [Np[:, j].reshape(32, 32) for j in range(r1)]
    # Stage 2: real-linear constraints in the reduced space.
    # Unknowns c in C^r1 (as real [Re c; Im c]); X = sum_j c_j B_j.
    def vr(Mm):
        return np.concatenate([Mm.real.ravel(), Mm.imag.ravel()])
    cols = []
    for j in range(r1):
        Bj = Bm[j]
        v = [_vr(Bj @ M - M @ Bj) for M in Ym]          # [X, pi^circ]=0
        v.append(_vr(Bj @ D - D @ Bj))                   # [X, D]=0
        v.append(_vr(Bj @ U - U @ Bj.conj()))            # XU = U Xbar
        v.append(_vr(Bj @ G - G @ Bj))                   # [X, Gamma]=0
        cols.append(np.concatenate(v))
    # c complex: F_re @ [Re c; Im c]; build via real/imag parts of cols
    C = np.stack(cols, axis=1)  # (rows, r1) complex
    F = np.block([[C.real, -C.imag], [C.imag, C.real]])
    s = np.linalg.svd(F, compute_uv=False)
    smax = s[0] if s[0] > 0 else 1.0
    return int(np.sum(s <= TOL * smax))


def control_orientability_SM():
    """Bicommutant orientability test on the SM triple (common.pi, DF_oneGen)."""
    gens = af_generators()
    D = DF_ref(); G = gamma_F()
    S = [sm_pi(g) for g in gens]
    S = S + [D @ M - M @ D for M in S]
    rows = []
    for M in S:
        rows.append(np.kron(M.T, np.eye(32)) - np.kron(np.eye(32), M))
    F = np.vstack(rows)
    _, s_, Vh = np.linalg.svd(F, full_matrices=False)
    smax = s_[0] if s_[0] > 0 else 1.0
    nul = int(np.sum(s_ <= TOL * smax))
    worst = 0.0
    for j in range(nul):
        X = Vh[-(nul - j), :].reshape(32, 32)
        nX = np.linalg.norm(X)
        if nX > 0:
            worst = max(worst, np.linalg.norm(G @ X - X @ G) / nX)
    return (worst < TOL), worst, nul


# ----------------------------------------------------------------------------
# Scan
# ----------------------------------------------------------------------------
def scan_one(blocks):
    d = irrep_dim(*blocks[0])
    Ds = [sample_D(blocks, i) for i in range(3)]
    ir_nuls = [irreducibility_nullity(d, D) for D in Ds]
    ir_pass = all(n == 1 for n in ir_nuls)
    # Orientability: 1 sample (provably universal-fail under the folded probe;
    # the single sample documents the residual).
    or_p, or_r = orientability(blocks, Ds[0])
    return dict(name=algebra_name(blocks), rdim=sum(real_dim(*b) for b in blocks), d=d,
                ir_nullities=ir_nuls, ir_pass=bool(ir_pass),
                or_pass=bool(or_p), or_residual=float(or_r))


def _worker(blocks):
    try:
        return scan_one(blocks), None
    except Exception as e:  # never let one algebra kill the scan
        return None, f"{algebra_name(blocks)}: {type(e).__name__}: {e}"


def main():
    t0 = time.time()
    cats = catalogue()
    print(f"catalogue: {len(cats)} algebras", flush=True)
    # warm caches in main process (also validates fb nullities vs corner rank)
    types = sorted({b[0] for b in cats})
    for (n, K) in types:
        fb = fb_data(n, K)
        _, rc, _ = ce_corner_rank([(n, K)])
        assert fb['nul'] == 272 - rc, (n, K, fb['nul'], rc)
    print(f"fb nullspaces ok ({len(types)} types)", flush=True)
    for d in sorted({irrep_dim(*t) for t in types}):
        st = ir_setup(d)
        exp = 2 + 2 * (8 - d) ** 2 + 128
        assert st['jg_nul'] == exp, (d, st['jg_nul'], exp)
    print("irreducibility J/Gamma reduction ok", flush=True)

    results, errors = [], []
    # Warm caches BEFORE forking so workers inherit them (fork on Linux).
    for (n, K) in types:
        fb_data(n, K)
    for d in sorted({irrep_dim(*t) for t in types}):
        ir_setup(d)
    print("caches warmed", flush=True)
    with Pool(NWORKERS) as pool:
        for i, (res, err) in enumerate(pool.imap_unordered(_worker, cats, chunksize=16)):
            if err:
                errors.append(err)
            else:
                results.append(res)
            if (i + 1) % 1000 == 0:
                print(f"  {i+1}/{len(cats)} ...", flush=True)
    print(f"errors: {len(errors)}", flush=True)
    for e in errors[:10]:
        print("  ERR", e)

    ir_pass_n = sum(1 for r in results if r['ir_pass'])
    or_pass_n = sum(1 for r in results if r['or_pass'])
    both_n = sum(1 for r in results if r['ir_pass'] and r['or_pass'])
    # split distribution for irreducibility
    from collections import Counter
    split = Counter(sum(1 for n in r['ir_nullities'] if n == 1) for r in results)
    af = [r for r in results if r['name'] == 'C+H+M_3(C)']
    out = dict(n_total=len(cats), n_ok=len(results),
               n_ir_pass=ir_pass_n, n_or_pass=or_pass_n, n_both=both_n,
               ir_split={str(k): v for k, v in sorted(split.items())},
               af=af[0] if af else None,
               results=results, errors=errors,
               wall_s=round(time.time() - t0, 1))
    with open('attack3_results.json', 'w') as f:
        json.dump(out, f)
    print(f"irreducibility all-3 pass: {ir_pass_n}/{len(results)}")
    print(f"orientability (1 sample) pass: {or_pass_n}/{len(results)}")
    print(f"both:                      {both_n}/{len(results)}")
    print(f"ir split (npass->count):    {dict(sorted(split.items()))}")
    print(f"A_F: {af[0] if af else None}")
    print(f"wall {time.time()-t0:.0f}s; wrote attack3_results.json")


def selftest():
    print("== fb nullspace vs corner rank ==")
    for (n, K) in [(1, 'R'), (1, 'C'), (1, 'H'), (2, 'R'), (2, 'C'),
                   (2, 'H'), (3, 'R'), (3, 'C'), (4, 'R'), (4, 'C'), (5, 'R')]:
        fb = fb_data(n, K)
        _, rc, _ = ce_corner_rank([(n, K)])
        print((n, K), "nul:", fb['nul'], "272-rank:", 272 - rc,
              "OK" if fb['nul'] == 272 - rc else "MISMATCH")
    print("== irreducibility reduction vs full system ==")
    for (n, K) in [(1, 'C'), (2, 'H')]:
        d = irrep_dim(n, K)
        D = sample_D([(n, K)], 0)
        n_red = irreducibility_nullity(d, D)
        gens = block_generators(n, K)
        Xm = []
        for Gg in gens:
            M = np.zeros((32, 32), complex); M[:d, :d] = Gg; Xm.append(M)
        Ym = [piOp(M) for M in Xm]
        n_full = commutant_nullity_real(Xm + Ym, D=D, use_J=True, use_Gamma=True)
        print((n, K), "reduced:", n_red, "full:", n_full,
              "OK" if n_red == n_full else "MISMATCH")
    print("== Poincare literal (A_F control) ==")
    AF = [(1, 'C'), (1, 'H'), (3, 'C')]
    Cap, ad = poincare_cap_literal(AF)
    print("Cap=\n", Cap, "\n|det| =", ad)
    print("== KO signs ==")
    print(ko_check(DF_ref()))


if __name__ == '__main__':
    if '--selftest' in sys.argv:
        selftest()
    elif '--controls' in sys.argv:
        # Scan-relevant controls: A_F under the asymmetric probe (fast).
        # (The SM-triple variants are valid but their SVDs are too large for
        #  the time budget; the irreducibility method itself is validated by
        #  reduced==full on (1,C) in --selftest.)
        AF = [(1, 'C'), (1, 'H'), (3, 'C')]
        d = irrep_dim(1, 'C')
        print("A_F controls (asymmetric probe):", flush=True)
        ok = True
        for i in range(3):
            D = sample_D(AF, i)
            n = irreducibility_nullity(d, D)
            p = (n == 1); ok &= p
            print(f"  irreducibility sample {i}: nullity={n} ->",
                  "PASS" if p else "FAIL", flush=True)
        print(f"  D-independent commutant nullity (complex): "
              f"{d_independent_commutant_nullity(d)}", flush=True)
        p, r = orientability(AF, sample_D(AF, 0))
        print(f"  orientability: pass={p} resid={r:.2e} ->",
              "PASS" if p else "FAIL (probe-limited, see report)", flush=True)
        Cap, ad = poincare_cap_literal(AF)
        print(f"  poincare |det|={ad:.2e} ->",
              "PASS" if ad > TOL else "FAIL (convention obstruction, see report)",
              flush=True)
        kc = ko_check(DF_ref())
        print("  KO:", kc, flush=True)
        kok = (kc['J2_resid'] < TOL and kc['JG_resid'] < TOL
               and kc['Dbasis_J_resid'] < TOL and kc['JD_resid'] < TOL)
        print("  KO ->", "PASS" if kok else "FAIL", flush=True)
    elif '--scan' in sys.argv:
        os.chdir(os.path.dirname(os.path.abspath(__file__)) + '/../..')
        main()
    else:
        print(__doc__)
