import ThetLogos.Axioms
import ThetLogos.TRO
import ThetLogos.Scaffold32
import ThetLogos.FiniteSpectralTriple
import ThetLogos.MartinettiRep
import ThetLogos.OrderOne
import ThetLogos.ThermalKMS
import ThetLogos.ModularTime
import ThetLogos.Chromatic
import ThetLogos.BlockedQuestions
import ThetLogos.ThreeGen
